[@@@ocamlformat "disable"]
(* Generated by ofpp to-ml from topology UnixDhcp. *)

module type Backend = Vnetif.BACKEND
module type Net = Mirage_net.S
module Net : Net
module Unikernel : sig end

val connect : Net.t Lwt.t Lazy.t

val start : unit Lwt.t Lazy.t
