(** Tests for {!Fpp.Gen_ml}: FPP to OCaml code generation.

    Each test shows the exact generated OCaml for a given FPP input. The tests
    serve as living documentation of the codegen: if the output changes, the
    diff tells you exactly what happened.

    {b State machine features}: simple transitions, typed signals,
    actions/guards, choices, nested states, entry/exit actions, do-actions,
    typed actions/guards, choice chains, inherited transitions, type definitions
    (enums, structs, arrays), catch-all patterns, external (bodyless) state
    machines.

    {b Topology features}: topologies, typed ports, functor application, default
    functor convention, topology import, ocaml.type annotations, passive
    components, bound leaf instances. *)

(* ── Helpers ─────────────────────────────────────────────────────── *)

let parse s =
  match Fpp.parse_string s with
  | tu -> tu
  | exception Fpp.Parse_error e ->
      Alcotest.failf "parse error: %a" Fpp.pp_error e

let render s =
  let tu = parse s in
  let sms = Fpp.state_machines tu in
  let buf = Buffer.create 256 in
  let ppf = Format.formatter_of_buffer buf in
  List.iter (Fpp.Gen_ml.pp ppf) sms;
  Format.pp_print_flush ppf ();
  Buffer.contents buf

let render_topo s =
  let tu = parse s in
  let topos = Fpp.topologies tu in
  let buf = Buffer.create 256 in
  let ppf = Format.formatter_of_buffer buf in
  List.iter (Fpp.Gen_ml.pp_topology tu ppf) topos;
  Format.pp_print_flush ppf ();
  Buffer.contents buf

let render_topo_mli s =
  let tu = parse s in
  let topos = Fpp.topologies tu in
  let buf = Buffer.create 256 in
  let ppf = Format.formatter_of_buffer buf in
  List.iter (Fpp.Gen_ml.pp_topology_mli tu ppf) topos;
  Format.pp_print_flush ppf ();
  Buffer.contents buf

let strip_trailing_ws s =
  String.split_on_char '\n' s
  |> List.map (fun line ->
      let len = String.length line in
      let i = ref (len - 1) in
      while !i >= 0 && (line.[!i] = ' ' || line.[!i] = '\t') do
        decr i
      done;
      String.sub line 0 (!i + 1))
  |> String.concat "\n"

let check_output ~msg actual expected =
  Alcotest.(check string)
    msg
    (strip_trailing_ws (String.trim expected))
    (strip_trailing_ws (String.trim actual))

(* ── State machines: basic ───────────────────────────────────────── *)

let test_simple_sm () =
  check_output ~msg:"two states, one signal"
    (render
       {|
    state machine M {
      signal s
      initial enter S1
      state S1 { on s enter S2 }
      state S2
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)
type s1
type s2

type _ state =
  | S1 : s1 state
  | S2 : s2 state

type any = State : _ state -> any

type signal =
  | S

module Make : sig
  type t
  val create : unit -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any }

  let state t = t.state

  let step t signal =
    match t.state, signal with
    | State S1, S ->
        { state = State S2 }
    | _ -> t

  let create () =
    { state = State S1 }
end|}

let test_typed_signal () =
  check_output ~msg:"signal carrying U32"
    (render
       {|
    state machine M {
      signal s : U32
      initial enter S
      state S { on s enter S }
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)
type s

type _ state =
  | S : s state

type any = State : _ state -> any

type signal =
  | S of int32

module Make : sig
  type t
  val create : unit -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any }

  let state t = t.state

  let step t signal =
    match t.state, signal with
    | State S, S s ->
        { state = State S }

  let create () =
    { state = State S }
end|}

let test_guard_choice () =
  check_output ~msg:"guard + choice + action"
    (render
       {|
    state machine M {
      action a1
      guard g
      signal s
      initial enter C
      state S
      choice C { if g do { a1 } enter S else enter S }
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)
type s

type _ state =
  | S : s state

type any = State : _ state -> any

type signal =
  | S

module type ACTIONS = sig
  type ctx
  val a1 : ctx -> unit
end

module type GUARDS = sig
  type ctx
  val g : ctx -> bool
end

module Make (A : ACTIONS) (G : GUARDS with type ctx = A.ctx) : sig
  type t
  val create : A.ctx -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any; ctx : A.ctx }

  let state t = t.state

  let enter_c t =
    if G.g t.ctx then (
      A.a1 t.ctx;
      { t with state = State S })
    else (
      { t with state = State S })

  let step t signal =
    match t.state, signal with
    | _ -> t

  let create ctx =
    let t = { state = State S; ctx } in
    enter_c t
end|}

let test_nested_state () =
  check_output ~msg:"composite state resolves to leaf"
    (render
       {|
    state machine M {
      initial enter S
      state S {
        initial enter T
        state T
      }
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)
type t

type _ state =
  | T : t state

type any = State : _ state -> any

module Make : sig
  type t
  val create : unit -> t
  val state : t -> any
end = struct
  type t = { state : any }

  let state t = t.state

  let create () =
    { state = State T }
end|}

let test_door () =
  check_output ~msg:"guards, actions, two signals"
    (render
       {|
    state machine Door {
      action lock
      guard locked
      signal open
      signal close
      initial enter Closed
      state Closed { on open if locked enter Closed
                     on open enter Opened }
      state Opened { on close do { lock } enter Closed }
    } |})
    {|(* Generated by ofpp to-ml from state machine Door *)
type closed
type opened

type _ state =
  | Closed : closed state
  | Opened : opened state

type any = State : _ state -> any

type signal =
  | Open
  | Close

module type ACTIONS = sig
  type ctx
  val lock : ctx -> unit
end

module type GUARDS = sig
  type ctx
  val locked : ctx -> bool
end

module Make (A : ACTIONS) (G : GUARDS with type ctx = A.ctx) : sig
  type t
  val create : A.ctx -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any; ctx : A.ctx }

  let state t = t.state

  let step t signal =
    match t.state, signal with
    | State Closed, Open ->
        if G.locked t.ctx then begin
        { t with state = State Closed }
        end
        else begin
        { t with state = State Opened }
        end
    | State Closed, _ -> t
    | State Opened, Close ->
        A.lock t.ctx;
        { t with state = State Closed }
    | State Opened, _ -> t

  let create ctx =
    { state = State Closed; ctx }
end|}

(* ── State machines: entry/exit, do, typed, inherited ────────────── *)

let test_entry_exit_actions () =
  check_output ~msg:"entry/exit hooks in step"
    (render
       {|
    state machine M {
      action on_enter_a
      action on_exit_a
      action on_enter_b
      signal go
      initial enter A
      state A { entry do { on_enter_a } exit do { on_exit_a } on go enter B }
      state B { entry do { on_enter_b } }
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)
type a
type b

type _ state =
  | A : a state
  | B : b state

type any = State : _ state -> any

type signal =
  | Go

module type ACTIONS = sig
  type ctx
  val on_enter_a : ctx -> unit
  val on_exit_a : ctx -> unit
  val on_enter_b : ctx -> unit
end

module Make (A : ACTIONS) : sig
  type t
  val create : A.ctx -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any; ctx : A.ctx }

  let state t = t.state

  let step t signal =
    match t.state, signal with
    | State A, Go ->
        A.on_exit_a t.ctx;
        A.on_enter_b t.ctx;
        { t with state = State B }
    | _ -> t

  let create ctx =
    A.on_enter_a ctx;
    { state = State A; ctx }
end|}

let test_do_action () =
  check_output ~msg:"do without state change"
    (render
       {|
    state machine M {
      action bump
      signal tick
      initial enter Running
      state Running { on tick do { bump } }
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)
type running

type _ state =
  | Running : running state

type any = State : _ state -> any

type signal =
  | Tick

module type ACTIONS = sig
  type ctx
  val bump : ctx -> unit
end

module Make (A : ACTIONS) : sig
  type t
  val create : A.ctx -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any; ctx : A.ctx }

  let state t = t.state

  let step t signal =
    match t.state, signal with
    | State Running, Tick ->
        A.bump t.ctx;
        t

  let create ctx =
    { state = State Running; ctx }
end|}

let test_typed_action_guard () =
  check_output ~msg:"typed action and guard with U32"
    (render
       {|
    state machine M {
      action report : U32
      guard over_limit : U32
      signal reading : U32
      initial enter Idle
      state Idle { on reading if over_limit do { report } enter Idle
                   on reading enter Idle }
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)
type idle

type _ state =
  | Idle : idle state

type any = State : _ state -> any

type signal =
  | Reading of int32

module type ACTIONS = sig
  type ctx
  val report : ctx -> int32 -> unit
end

module type GUARDS = sig
  type ctx
  val over_limit : ctx -> int32 -> bool
end

module Make (A : ACTIONS) (G : GUARDS with type ctx = A.ctx) : sig
  type t
  val create : A.ctx -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any; ctx : A.ctx }

  let state t = t.state

  let step t signal =
    match t.state, signal with
    | State Idle, Reading reading ->
        if G.over_limit t.ctx reading then begin
        A.report t.ctx reading;
        { t with state = State Idle }
        end
        else begin
        { t with state = State Idle }
        end

  let create ctx =
    { state = State Idle; ctx }
end|}

let test_choice_chain () =
  check_output ~msg:"choices targeting choices need let rec"
    (render
       {|
    state machine M {
      guard g1
      guard g2
      signal s
      initial enter S1
      state S1 { on s enter C1 }
      state S2
      state S3
      choice C1 { if g1 enter S2 else enter C2 }
      choice C2 { if g2 enter S3 else enter S1 }
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)
type s1
type s2
type s3

type _ state =
  | S1 : s1 state
  | S2 : s2 state
  | S3 : s3 state

type any = State : _ state -> any

type signal =
  | S

module type GUARDS = sig
  type ctx
  val g1 : ctx -> bool
  val g2 : ctx -> bool
end

module Make (G : GUARDS) : sig
  type t
  val create : G.ctx -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any; ctx : G.ctx }

  let state t = t.state

  let rec enter_c1 t =
    if G.g1 t.ctx then (
      { t with state = State S2 })
    else (
      enter_c2 t)

  and enter_c2 t =
    if G.g2 t.ctx then (
      { t with state = State S3 })
    else (
      { t with state = State S1 })

  let step t signal =
    match t.state, signal with
    | State S1, S ->
        enter_c1 t
    | _ -> t

  let create ctx =
    { state = State S1; ctx }
end|}

let test_inherited_transition () =
  check_output ~msg:"parent transition visible in child leaf"
    (render
       {|
    state machine M {
      signal alarm
      signal tick
      initial enter Running
      state Running {
        on alarm enter Stopped
        initial enter Counting
        state Counting { on tick enter Counting }
      }
      state Stopped
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)
type counting
type stopped

type _ state =
  | Counting : counting state
  | Stopped : stopped state

type any = State : _ state -> any

type signal =
  | Alarm
  | Tick

module Make : sig
  type t
  val create : unit -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any }

  let state t = t.state

  let step t signal =
    match t.state, signal with
    | State Counting, Alarm ->
        { state = State Stopped }
    | State Counting, Tick ->
        { state = State Counting }
    | _ -> t

  let create () =
    { state = State Counting }
end|}

(* ── State machines: type definitions ────────────────────────────── *)

let test_enum_type () =
  check_output ~msg:"enum inside state machine"
    (render
       {|
    state machine M {
      enum Color { RED, GREEN, BLUE }
      signal s
      initial enter S
      state S
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)

type color =
  | Red
  | Green
  | Blue
type s

type _ state =
  | S : s state

type any = State : _ state -> any

type signal =
  | S

module Make : sig
  type t
  val create : unit -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any }

  let state t = t.state

  let step t signal =
    match t.state, signal with
    | _ -> t

  let create () =
    { state = State S }
end|}

let test_struct_type () =
  check_output ~msg:"struct inside state machine"
    (render
       {|
    state machine M {
      struct Point { x: F64, y: F64 }
      signal s
      initial enter S
      state S
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)

type point = {
  x : float;
  y : float;
}
type s

type _ state =
  | S : s state

type any = State : _ state -> any

type signal =
  | S

module Make : sig
  type t
  val create : unit -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any }

  let state t = t.state

  let step t signal =
    match t.state, signal with
    | _ -> t

  let create () =
    { state = State S }
end|}

let test_array_type () =
  check_output ~msg:"array inside state machine"
    (render
       {|
    state machine M {
      array Readings = [10] F64
      signal s
      initial enter S
      state S
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)

type readings = float array
type s

type _ state =
  | S : s state

type any = State : _ state -> any

type signal =
  | S

module Make : sig
  type t
  val create : unit -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any }

  let state t = t.state

  let step t signal =
    match t.state, signal with
    | _ -> t

  let create () =
    { state = State S }
end|}

(* ── State machines: edge cases ──────────────────────────────────── *)

let test_external_sm () =
  check_output ~msg:"bodyless state machine produces nothing"
    (render {| state machine External |})
    ""

let test_catchall_pattern () =
  check_output ~msg:"partial signal coverage emits per-state + final catchall"
    (render
       {|
    state machine M {
      signal a
      signal b
      signal c
      initial enter S1
      state S1 { on a enter S2 }
      state S2
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)
type s1
type s2

type _ state =
  | S1 : s1 state
  | S2 : s2 state

type any = State : _ state -> any

type signal =
  | A
  | B
  | C

module Make : sig
  type t
  val create : unit -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any }

  let state t = t.state

  let step t signal =
    match t.state, signal with
    | State S1, A ->
        { state = State S2 }
    | State S1, _ -> t
    | _ -> t

  let create () =
    { state = State S1 }
end|}

(* ── Topology: default (unannotated) mode ────────────────────────── *)

let test_simple_topology () =
  check_output ~msg:"passive components, functor application"
    (render_topo
       {|
    port P
    passive component Sensor { output port dataOut: P }
    passive component Logger { sync input port dataIn: P }
    instance sensor: Sensor base id 0x100
    instance logger: Logger base id 0x200
    topology System {
      instance sensor
      instance logger
      connections Data { sensor.dataOut -> logger.dataIn }
    } |})
    {|(* Generated by ofpp to-ml from topology System *)

module Sensor = Sensor.Make(Logger)

open Lwt.Syntax

let data = lazy (
  let* logger = Logger.data_in () in
  Sensor.connect logger)|}

let test_typed_port_topology () =
  check_output ~msg:"typed ports"
    (render_topo
       {|
    port DataPort(value: U32) -> bool
    passive component Producer { output port out: DataPort }
    passive component Consumer { sync input port in_: DataPort }
    instance producer: Producer base id 0x100
    instance consumer: Consumer base id 0x200
    topology App {
      instance producer
      instance consumer
      connections Main { producer.out -> consumer.in_ }
    } |})
    {|(* Generated by ofpp to-ml from topology App *)

module Producer = Producer.Make(Consumer)

open Lwt.Syntax

let main = lazy (
  let* consumer = Consumer.in_ () in
  Producer.connect consumer)|}

(* ── Topology: functor-application ────────────────────────────────── *)

let test_annotated_topology () =
  check_output ~msg:"functor apps, auto-inferred connect args, Lwt"
    (render_topo
       {|
    port P
    active component Net { sync input port write: P }
    @ ocaml.module Eth.Make
    active component Ethernet {
      output port net: P
    }
    @ ocaml.module Ipv4.Make
    active component Ipv4 {
      output port eth: P
      sync input port cidr: P
    }
    instance net: Net base id 0x100
    instance eth: Ethernet base id 0x200
    instance ipv4: Ipv4 base id 0x300
    topology Stack {
      instance net
      instance eth
      instance ipv4
      connections W {
        eth.net -> net.write
        ipv4.eth -> eth.write
      }
    } |})
    {|(* Generated by ofpp to-ml from topology Stack *)

module Eth = Eth.Make(Net)
module Ipv4 = Ipv4.Make(Eth)

open Lwt.Syntax

let w = lazy (
  let* net = Net.write () in
  let* eth = Eth.connect net in
  Ipv4.cidr eth)|}

let test_annotated_default_functor () =
  check_output ~msg:"ComponentName.Make convention"
    (render_topo
       {|
    port P
    @ ocaml.module Foo.Make
    active component Foo { output port out: P }
    active component Bar { sync input port in_: P }
    instance foo: Foo base id 0x100
    instance bar: Bar base id 0x200
    topology T {
      instance foo
      instance bar
      connections C { foo.out -> bar.in_ }
    } |})
    {|(* Generated by ofpp to-ml from topology T *)

module Foo = Foo.Make(Bar)

open Lwt.Syntax

let c = lazy (
  let* bar = Bar.in_ () in
  Foo.connect bar)|}

let test_module_nested_default_functor () =
  check_output ~msg:"Instance name -> Instance_name.Make convention"
    (render_topo
       {|
    port P
    active component Net { sync input port write: P }
    module Tcp {
      active component Flow {
        output port net: P
        sync input port write: P
      }
    }
    instance net: Net base id 0x100
    instance tcp: Tcp.Flow base id 0x200
    topology T {
      instance net
      instance tcp
      connections C { tcp.net -> net.write }
    } |})
    {|(* Generated by ofpp to-ml from topology T *)

module Tcp = Tcp.Flow(Net)

open Lwt.Syntax

let c = lazy (
  let* net = Net.write () in
  Tcp.write net)|}

let test_topology_import () =
  check_output ~msg:"import merges public instances"
    (render_topo
       {|
    port P
    active component Net { sync input port write: P }
    @ ocaml.module Eth.Make
    active component Eth {
      output port net: P
    }
    active component Srv { output port eth: P }
    instance net: Net base id 0x100
    instance eth: Eth base id 0x200
    instance srv: Srv base id 0x300
    topology Base {
      instance net
      instance eth
      connections W { eth.net -> net.write }
    }
    topology App {
      import Base
      instance srv
      connections W { srv.eth -> eth.write }
    } |})
    {|(* Generated by ofpp to-ml from topology Base *)

module Eth = Eth.Make(Net)

open Lwt.Syntax

let w = lazy (
  let* net = Net.write () in
  Eth.connect net)
(* Generated by ofpp to-ml from topology App *)

module Eth = Eth.Make(Net)
module Srv = Srv.Make(Eth)

open Lwt.Syntax

let w = lazy (
  let* net = Net.write () in
  let* eth = Eth.connect net in
  Srv.connect eth)|}

let test_passive_in_annotated () =
  check_output ~msg:"passive participates in record and connect"
    (render_topo
       {|
    port P
    @ ocaml.module Crunch.Make
    passive component Kv { output port dep: P }
    active component Http { sync input port static: P }
    instance kv: Kv base id 0x100
    instance http: Http base id 0x200
    topology T {
      instance kv
      instance http
      connections C { kv.dep -> http.static }
    } |})
    {|(* Generated by ofpp to-ml from topology T *)

module Kv = Crunch.Make(Http)

open Lwt.Syntax

let c = lazy (
  let* http = Http.static () in
  Kv.connect http)|}

(* ── Module type generation ──────────────────────────────────────── *)

let test_external_types () =
  check_output ~msg:"ocaml.type maps FPP types to OCaml"
    (render_topo
       {|
    @ ocaml.type Cstruct.t
    type Buffer
    type Macaddr
    port Write(data: Buffer)
    port GetMac -> Macaddr
    active component Net {
      sync input port write: Write
      sync input port mac: GetMac
    }
    active component Eth {
      output port net: Write
      sync input port write: Write
    }
    instance net: Net base id 0x100
    instance eth: Eth base id 0x200
    topology T {
      instance net
      instance eth
      connections C { eth.net -> net.write }
    } |})
    {|(* Generated by ofpp to-ml from topology T *)

module Eth = Eth.Make(Net)

open Lwt.Syntax

let c = lazy (
  let* net = Net.write () in
  Eth.write net)|}

(* ── Bound leaf instances ────────────────────────────────────────── *)

let test_bound_leaf_instance () =
  check_output ~msg:"@ ocaml.module binds leaf, auto-inits in connect"
    (render_topo
       {|
    port P
    @ ocaml.module Eth.Make
    active component Eth {
      output port net: P
    }
    active component Net { sync input port write: P }
    active component Kv { sync input port get: P }
    instance net: Net base id 0x100
    instance eth: Eth base id 0x200
    instance data: Kv base id 0x300
    topology T {
      instance net
      instance eth
      @ ocaml.module Htdocs_data
      instance data
      connections W { eth.net -> net.write }
    } |})
    {|(* Generated by ofpp to-ml from topology T *)

module Data = Htdocs_data
module Eth = Eth.Make(Net)

open Lwt.Syntax

let w = lazy (
  let* net = Net.write () in
  Eth.connect net)

let get = lazy (Data.get ())|}

let test_mixed_bound_unbound () =
  check_output ~msg:"bound + unbound leaves, functor params only for unbound"
    (render_topo
       {|
    port P
    @ ocaml.module Srv.Make
    active component Srv {
      output port kv: P
      output port certs: P
    }
    active component Kv { sync input port get: P }
    instance kv: Kv base id 0x100
    instance certs: Kv base id 0x200
    instance srv: Srv base id 0x300
    topology T {
      @ ocaml.module Static_data
      instance kv
      instance certs
      instance srv
      connections W {
        srv.kv -> kv.get
        srv.certs -> certs.get
      }
    } |})
    {|(* Generated by ofpp to-ml from topology T *)

module Kv = Static_data
module Srv = Srv.Make(Kv)(Certs)

open Lwt.Syntax

let w = lazy (
  let* kv = Kv.get () in
  let* certs = Certs.get () in
  Srv.connect kv certs)|}

let test_all_leaves_bound () =
  check_output ~msg:"all leaves bound, top-level lazy bindings"
    (render_topo
       {|
    port P
    @ ocaml.module Srv.Make
    active component Srv {
      output port kv: P
    }
    active component Kv { sync input port get: P }
    instance kv: Kv base id 0x100
    instance srv: Srv base id 0x200
    topology T {
      @ ocaml.module Embedded_data
      instance kv
      instance srv
      connections W { srv.kv -> kv.get }
    } |})
    {|(* Generated by ofpp to-ml from topology T *)

module Kv = Embedded_data
module Srv = Srv.Make(Kv)

open Lwt.Syntax

let w = lazy (
  let* kv = Kv.get () in
  Srv.connect kv)|}

(* ── Topology: multiple named connection groups ──────────────────── *)

let test_multi_group () =
  check_output ~msg:"backward deps merge groups into one function"
    (render_topo
       {|
    port P
    passive component A { output port out: P }
    passive component B {
      output port out: P
      sync input port in_: P
    }
    passive component C { sync input port in_: P }
    instance a: A base id 0x100
    instance b: B base id 0x200
    instance c: C base id 0x300
    topology T {
      instance a
      instance b
      instance c
      connections Connect { a.out -> b.in_ }
      connections Start { b.out -> c.in_ }
    } |})
    {|(* Generated by ofpp to-ml from topology T *)

module B = B.Make(C)
module A = A.Make(B)

open Lwt.Syntax

let connect = lazy (
  let* c = C.in_ () in
  let* b = B.in_ c in
  A.connect b)|}

(* ── Topology: empty ──────────────────────────────────────────────── *)

let test_empty_topology () =
  check_output ~msg:"empty topology emits no output"
    (render_topo {|
    topology Empty {
    } |})
    {||}

(* ── Bound non-leaf instances ─────────────────────────────────────── *)

let test_bound_nonleaf () =
  check_output ~msg:"bound non-leaf gets top-level lazy with deps"
    (render_topo
       {|
    port P
    port Dep
    @ ocaml.module Srv.Make
    active component Srv {
      output port stack: Dep
    }
    active component Stack {
      sync input port provide: Dep
    }
    instance stack: Stack base id 0x100
    instance srv: Srv base id 0x200
    topology T {
      @ ocaml.module Tcpip_stack_socket.V4V6
      instance stack
      instance srv
      connections W { srv.stack -> stack.provide }
    } |})
    {|(* Generated by ofpp to-ml from topology T *)

module Stack = Tcpip_stack_socket.V4V6
module Srv = Srv.Make(Stack)

open Lwt.Syntax

let w = lazy (
  let* stack = Stack.provide () in
  Srv.connect stack)|}

(* ── Topology: custom group name ──────────────────────────────────── *)

let test_custom_group_name () =
  check_output ~msg:"group name propagates to val and calls"
    (render_topo
       {|
    port P
    passive component Sensor { output port dataOut: P }
    passive component Logger { sync input port dataIn: P }
    instance sensor: Sensor base id 0x100
    instance logger: Logger base id 0x200
    topology System {
      instance sensor
      instance logger
      connections ConnectDevice { sensor.dataOut -> logger.dataIn }
    } |})
    {|(* Generated by ofpp to-ml from topology System *)

module Sensor = Sensor.Make(Logger)

open Lwt.Syntax

let connect_device = lazy (
  let* logger = Logger.data_in () in
  Sensor.connect logger)|}

(* ── Topology: runtime component convention ───────────────────────── *)

let test_runtime () =
  check_output ~msg:"bound runtime labelled args inject thunk calls"
    (render_topo
       {|
    port P
    passive component Runtime {
      output port ipv4_only: serial
      output port ipv6_only: serial
    }
    active component Socket { sync input port connect: P }
    @ ocaml.module Srv.Make
    active component Srv { output port sock: P }
    instance runtime: Runtime base id 0xB00
    instance sock: Socket base id 0x100
    instance srv: Srv base id 0x200
    topology T {
      @ ocaml.module My.Runtime
      instance runtime
      @ ocaml.module My.Socket
      instance sock
      instance srv
      connections Connect {
        runtime.ipv4_only -> sock.connect
        runtime.ipv6_only -> sock.connect
        srv.sock -> sock.connect
      }
    } |})
    {|(* Generated by ofpp to-ml from topology T *)

module Sock = My.Socket
module Srv = Srv.Make(Sock)

open Lwt.Syntax

let connect = lazy (
  let* sock = Sock.connect ~ipv4_only:(runtime__ipv4_only ()) ~ipv6_only:(runtime__ipv6_only ()) in
  Srv.connect sock)|}

let test_runtime_parameterised () =
  check_output ~msg:"unbound runtime labelled args become thunk calls"
    (render_topo
       {|
    port P
    passive component Runtime {
      output port ipv4_only: serial
      output port ipv6_only: serial
    }
    active component Socket { sync input port connect: P }
    active component Stack {
      output port udp: P
      output port tcp: P
    }
    instance runtime: Runtime base id 0xB00
    instance udp: Socket base id 0x100
    instance tcp: Socket base id 0x200
    instance stack: Stack base id 0x300
    topology T {
      instance runtime
      instance udp
      instance tcp
      instance stack
      connections Connect {
        runtime.ipv4_only -> udp.connect
        runtime.ipv6_only -> udp.connect
        runtime.ipv4_only -> tcp.connect
        runtime.ipv6_only -> tcp.connect
        stack.udp -> udp.connect
        stack.tcp -> tcp.connect
      }
    } |})
    {|(* Generated by ofpp to-ml from topology T *)

module Stack = Stack.Make(Udp)(Tcp)

open Lwt.Syntax

let connect = lazy (
  let* udp = Udp.connect ~ipv4_only:(runtime__ipv4_only ()) ~ipv6_only:(runtime__ipv6_only ()) in
  let* tcp = Tcp.connect ~ipv4_only:(runtime__ipv4_only ()) ~ipv6_only:(runtime__ipv6_only ()) in
  Stack.connect udp tcp)|}

(* ── Topology .mli: @ ocaml.sig ──────────────────────────────────── *)

let test_mli_sig_path () =
  check_output ~msg:"@ ocaml.sig emits module type constraint in .mli"
    (render_topo_mli
       {|
    port P
    @ ocaml.sig Net.S
    passive component Net { sync input port connect: serial }
    @ ocaml.sig Block.S
    passive component Block { sync input port connect: serial }
    passive component App {
      output port net: P
      output port block: P
      sync input port start: serial
    }
    instance net: Net base id 0x100
    instance block: Block base id 0x200
    instance app: App base id 0x300
    topology T {
      @ ocaml.module Unikernel
      instance net
      @ ocaml.module Ramdisk
      instance block
      instance app
      connections Start {
        app.net -> net.connect
        app.block -> block.connect
      }
    } |})
    {|(* Generated by ofpp to-ml from topology T. *)

module Net : Net.S
module Block : Block.S
module App : sig end

val start : unit Lwt.t Lazy.t|}

(* ── Topology .mli: typed ports ──────────────────────────────────── *)

let test_mli_typed_ports () =
  check_output ~msg:"typed input ports appear as val in .mli"
    (render_topo_mli
       {|
    @ ocaml.type Macaddr.t
    type Mac

    port GetMac -> Mac
    port GetMtu -> U32

    passive component Net { sync input port connect: serial }
    passive component Eth {
      sync input port connect: serial
      output port net: serial
      sync input port mac: GetMac
      sync input port mtu: GetMtu
    }
    instance netif: Net base id 0x100
    instance eth: Eth base id 0x200
    topology T {
      instance netif
      instance eth
      connections Connect {
        eth.net -> netif.connect
      }
    } |})
    {|(* Generated by ofpp to-ml from topology T. *)

module Eth : sig
  type t
  val mac : t -> Macaddr.t
  val mtu : t -> int32
end

val connect : Eth.t Lwt.t Lazy.t|}

(* ── Topology .mli: @ ocaml.sig + typed ports ────────────────────── *)

let test_mli_sig_with_typed_ports () =
  check_output
    ~msg:"@ ocaml.sig takes precedence; typed ports still appear in derived sig"
    (render_topo_mli
       {|
    @ ocaml.type Macaddr.t
    type Mac

    port GetMac -> Mac
    port GetMtu -> U32

    @ ocaml.sig Ethernet.S
    passive component Eth {
      sync input port connect: serial
      output port net: serial
      sync input port mac: GetMac
      sync input port mtu: GetMtu
    }
    passive component Net { sync input port connect: serial }
    passive component App {
      output port eth: serial
      sync input port start: serial
    }
    instance net: Net base id 0x100
    instance eth: Eth base id 0x200
    instance app: App base id 0x300
    topology T {
      instance net
      instance eth
      instance app
      connections Connect {
        eth.net -> net.connect
      }
      connections Start {
        app.eth -> eth.connect
      }
    } |})
    {|(* Generated by ofpp to-ml from topology T. *)

module type Eth = Ethernet.S
module Eth : Eth
module App : sig end

val connect : Eth.t Lwt.t Lazy.t

val start : unit Lwt.t Lazy.t|}

(* ── Suite ───────────────────────────────────────────────────────── *)

let suite =
  ( "gen_ml",
    [
      (* State machines — basic *)
      Alcotest.test_case "simple_sm" `Quick test_simple_sm;
      Alcotest.test_case "typed_signal" `Quick test_typed_signal;
      Alcotest.test_case "guard_choice" `Quick test_guard_choice;
      Alcotest.test_case "nested_state" `Quick test_nested_state;
      Alcotest.test_case "door" `Quick test_door;
      (* State machines — entry/exit, do, typed, inherited *)
      Alcotest.test_case "entry_exit_actions" `Quick test_entry_exit_actions;
      Alcotest.test_case "do_action" `Quick test_do_action;
      Alcotest.test_case "typed_action_guard" `Quick test_typed_action_guard;
      Alcotest.test_case "choice_chain" `Quick test_choice_chain;
      Alcotest.test_case "inherited_transition" `Quick test_inherited_transition;
      (* State machines — type definitions *)
      Alcotest.test_case "enum_type" `Quick test_enum_type;
      Alcotest.test_case "struct_type" `Quick test_struct_type;
      Alcotest.test_case "array_type" `Quick test_array_type;
      (* State machines — edge cases *)
      Alcotest.test_case "external_sm" `Quick test_external_sm;
      Alcotest.test_case "catchall_pattern" `Quick test_catchall_pattern;
      (* Topology — basic *)
      Alcotest.test_case "simple_topology" `Quick test_simple_topology;
      Alcotest.test_case "typed_port_topology" `Quick test_typed_port_topology;
      (* Topology — functor application *)
      Alcotest.test_case "annotated_topology" `Quick test_annotated_topology;
      Alcotest.test_case "annotated_default_functor" `Quick
        test_annotated_default_functor;
      Alcotest.test_case "module_nested_default_functor" `Quick
        test_module_nested_default_functor;
      Alcotest.test_case "topology_import" `Quick test_topology_import;
      Alcotest.test_case "passive_in_annotated" `Quick test_passive_in_annotated;
      (* Topology — bound leaf instances *)
      Alcotest.test_case "bound_leaf_instance" `Quick test_bound_leaf_instance;
      Alcotest.test_case "mixed_bound_unbound" `Quick test_mixed_bound_unbound;
      Alcotest.test_case "all_leaves_bound" `Quick test_all_leaves_bound;
      (* Module types *)
      Alcotest.test_case "external_types" `Quick test_external_types;
      (* Topology — bound non-leaf instances *)
      Alcotest.test_case "bound_nonleaf" `Quick test_bound_nonleaf;
      (* Topology — empty *)
      Alcotest.test_case "empty_topology" `Quick test_empty_topology;
      (* Topology — multiple groups *)
      Alcotest.test_case "multi_group" `Quick test_multi_group;
      (* Topology — custom group name *)
      Alcotest.test_case "custom_group_name" `Quick test_custom_group_name;
      (* Topology — runtime component *)
      Alcotest.test_case "runtime" `Quick test_runtime;
      Alcotest.test_case "runtime_unbound_labelled_args" `Quick
        test_runtime_parameterised;
      (* Topology — .mli sig_path *)
      Alcotest.test_case "mli_sig_path" `Quick test_mli_sig_path;
      Alcotest.test_case "mli_typed_ports" `Quick test_mli_typed_ports;
      Alcotest.test_case "mli_sig_with_typed_ports" `Quick
        test_mli_sig_with_typed_ports;
    ] )
