(** Tests for {!Fpp.Gen_ml}: FPP to OCaml code generation.

    Each test shows the exact generated OCaml for a given FPP input. The tests
    serve as living documentation of the codegen: if the output changes, the
    diff tells you exactly what happened.

    {b State machine features}: simple transitions, typed signals,
    actions/guards, choices, nested states, entry/exit actions, do-actions,
    typed actions/guards, choice chains, inherited transitions, type definitions
    (enums, structs, arrays), catch-all patterns, external (bodyless) state
    machines.

    {b Topology features}: passive default mode, typed ports, annotated
    functor-application mode, default functor convention, functor parameter
    lists, connect_args, ocaml.param ports, topology import, ocaml.sig /
    ocaml.type annotations, passive components in annotated mode. *)

(* ── Helpers ─────────────────────────────────────────────────────── *)

let parse s =
  match Fpp.parse_string s with
  | tu -> tu
  | exception Fpp.Parse_error e ->
      Alcotest.failf "parse error: %a" Fpp.pp_error e

let render s =
  let tu = parse s in
  let sms = Fpp.state_machines tu in
  let buf = Buffer.create 256 in
  let ppf = Format.formatter_of_buffer buf in
  List.iter (Fpp.Gen_ml.pp ppf) sms;
  Format.pp_print_flush ppf ();
  Buffer.contents buf

let render_topo s =
  let tu = parse s in
  let topos = Fpp.topologies tu in
  let buf = Buffer.create 256 in
  let ppf = Format.formatter_of_buffer buf in
  List.iter (Fpp.Gen_ml.pp_topology tu ppf) topos;
  Format.pp_print_flush ppf ();
  Buffer.contents buf

let render_module_types s =
  let tu = parse s in
  let buf = Buffer.create 256 in
  let ppf = Format.formatter_of_buffer buf in
  Fpp.Gen_ml.pp_module_types tu ppf;
  Format.pp_print_flush ppf ();
  Buffer.contents buf

let strip_trailing_ws s =
  String.split_on_char '\n' s
  |> List.map (fun line ->
      let len = String.length line in
      let i = ref (len - 1) in
      while !i >= 0 && (line.[!i] = ' ' || line.[!i] = '\t') do
        decr i
      done;
      String.sub line 0 (!i + 1))
  |> String.concat "\n"

let check_output ~msg actual expected =
  Alcotest.(check string)
    msg
    (strip_trailing_ws (String.trim expected))
    (strip_trailing_ws (String.trim actual))

(* ── State machines: basic ───────────────────────────────────────── *)

let test_simple_sm () =
  check_output ~msg:"two states, one signal"
    (render
       {|
    state machine M {
      signal s
      initial enter S1
      state S1 { on s enter S2 }
      state S2
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)
type s1
type s2

type _ state =
  | S1 : s1 state
  | S2 : s2 state

type any = State : _ state -> any

type signal =
  | S

module Make : sig
  type t
  val create : unit -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any }

  let state t = t.state

  let step t signal =
    match t.state, signal with
    | State S1, S ->
          { state = State S2 }
    | _ -> t

  let create () =
    { state = State S1 }
end|}

let test_typed_signal () =
  check_output ~msg:"signal carrying U32"
    (render
       {|
    state machine M {
      signal s : U32
      initial enter S
      state S { on s enter S }
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)
type s

type _ state =
  | S : s state

type any = State : _ state -> any

type signal =
  | S of int32

module Make : sig
  type t
  val create : unit -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any }

  let state t = t.state

  let step t signal =
    match t.state, signal with
    | State S, S _v ->
          { state = State S }

  let create () =
    { state = State S }
end|}

let test_guard_choice () =
  check_output ~msg:"guard + choice + action"
    (render
       {|
    state machine M {
      action a1
      guard g
      signal s
      initial enter C
      state S
      choice C { if g do { a1 } enter S else enter S }
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)
type s

type _ state =
  | S : s state

type any = State : _ state -> any

type signal =
  | S

module type ACTIONS = sig
  type ctx
  val a1 : ctx -> unit
end

module type GUARDS = sig
  type ctx
  val g : ctx -> bool
end

module Make (A : ACTIONS) (G : GUARDS with type ctx = A.ctx) : sig
  type t
  val create : A.ctx -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any; ctx : A.ctx }

  let state t = t.state

  let enter_c t =
    if G.g t.ctx then (
      A.a1 t.ctx;
      { t with state = State S })
    else (
      { t with state = State S })

  let step t signal =
    match t.state, signal with
    | _ -> t

  let create ctx =
    let t = { state = State S; ctx } in
    enter_c t
end|}

let test_nested_state () =
  check_output ~msg:"composite state resolves to leaf"
    (render
       {|
    state machine M {
      initial enter S
      state S {
        initial enter T
        state T
      }
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)
type t

type _ state =
  | T : t state

type any = State : _ state -> any

module Make : sig
  type t
  val create : unit -> t
  val state : t -> any
end = struct
  type t = { state : any }

  let state t = t.state

  let create () =
    { state = State T }
end|}

let test_door () =
  check_output ~msg:"guards, actions, two signals"
    (render
       {|
    state machine Door {
      action lock
      guard locked
      signal open
      signal close
      initial enter Closed
      state Closed { on open if locked enter Closed
                     on open enter Opened }
      state Opened { on close do { lock } enter Closed }
    } |})
    {|(* Generated by ofpp to-ml from state machine Door *)
type closed
type opened

type _ state =
  | Closed : closed state
  | Opened : opened state

type any = State : _ state -> any

type signal =
  | Open
  | Close

module type ACTIONS = sig
  type ctx
  val lock : ctx -> unit
end

module type GUARDS = sig
  type ctx
  val locked : ctx -> bool
end

module Make (A : ACTIONS) (G : GUARDS with type ctx = A.ctx) : sig
  type t
  val create : A.ctx -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any; ctx : A.ctx }

  let state t = t.state

  let step t signal =
    match t.state, signal with
    | State Closed, Open ->
        if G.locked t.ctx then begin
          { t with state = State Closed }
        end
        else begin
          { t with state = State Opened }
        end
    | State Closed, _ -> t
    | State Opened, Close ->
          A.lock t.ctx;
          { t with state = State Closed }
    | State Opened, _ -> t

  let create ctx =
    { state = State Closed; ctx }
end|}

(* ── State machines: entry/exit, do, typed, inherited ────────────── *)

let test_entry_exit_actions () =
  check_output ~msg:"entry/exit hooks in step"
    (render
       {|
    state machine M {
      action on_enter_a
      action on_exit_a
      action on_enter_b
      signal go
      initial enter A
      state A { entry do { on_enter_a } exit do { on_exit_a } on go enter B }
      state B { entry do { on_enter_b } }
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)
type a
type b

type _ state =
  | A : a state
  | B : b state

type any = State : _ state -> any

type signal =
  | Go

module type ACTIONS = sig
  type ctx
  val on_enter_a : ctx -> unit
  val on_exit_a : ctx -> unit
  val on_enter_b : ctx -> unit
end

module Make (A : ACTIONS) : sig
  type t
  val create : A.ctx -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any; ctx : A.ctx }

  let state t = t.state

  let step t signal =
    match t.state, signal with
    | State A, Go ->
        A.on_exit_a t.ctx;
          A.on_enter_b t.ctx;
          { t with state = State B }
    | _ -> t

  let create ctx =
    A.on_enter_a ctx;
    { state = State A; ctx }
end|}

let test_do_action () =
  check_output ~msg:"do without state change"
    (render
       {|
    state machine M {
      action bump
      signal tick
      initial enter Running
      state Running { on tick do { bump } }
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)
type running

type _ state =
  | Running : running state

type any = State : _ state -> any

type signal =
  | Tick

module type ACTIONS = sig
  type ctx
  val bump : ctx -> unit
end

module Make (A : ACTIONS) : sig
  type t
  val create : A.ctx -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any; ctx : A.ctx }

  let state t = t.state

  let step t signal =
    match t.state, signal with
    | State Running, Tick ->
          A.bump t.ctx;
          t

  let create ctx =
    { state = State Running; ctx }
end|}

let test_typed_action_guard () =
  check_output ~msg:"typed action and guard with U32"
    (render
       {|
    state machine M {
      action report : U32
      guard over_limit : U32
      signal reading : U32
      initial enter Idle
      state Idle { on reading if over_limit do { report } enter Idle
                   on reading enter Idle }
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)
type idle

type _ state =
  | Idle : idle state

type any = State : _ state -> any

type signal =
  | Reading of int32

module type ACTIONS = sig
  type ctx
  val report : ctx -> int32 -> unit
end

module type GUARDS = sig
  type ctx
  val over_limit : ctx -> int32 -> bool
end

module Make (A : ACTIONS) (G : GUARDS with type ctx = A.ctx) : sig
  type t
  val create : A.ctx -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any; ctx : A.ctx }

  let state t = t.state

  let step t signal =
    match t.state, signal with
    | State Idle, Reading _v ->
        if G.over_limit t.ctx _v then begin
          A.report t.ctx _v;
          { t with state = State Idle }
        end
        else begin
          { t with state = State Idle }
        end

  let create ctx =
    { state = State Idle; ctx }
end|}

let test_choice_chain () =
  check_output ~msg:"choices targeting choices need let rec"
    (render
       {|
    state machine M {
      guard g1
      guard g2
      signal s
      initial enter S1
      state S1 { on s enter C1 }
      state S2
      state S3
      choice C1 { if g1 enter S2 else enter C2 }
      choice C2 { if g2 enter S3 else enter S1 }
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)
type s1
type s2
type s3

type _ state =
  | S1 : s1 state
  | S2 : s2 state
  | S3 : s3 state

type any = State : _ state -> any

type signal =
  | S

module type GUARDS = sig
  type ctx
  val g1 : ctx -> bool
  val g2 : ctx -> bool
end

module Make (G : GUARDS) : sig
  type t
  val create : G.ctx -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any; ctx : G.ctx }

  let state t = t.state

  let rec enter_c1 t =
    if G.g1 t.ctx then (
      { t with state = State S2 })
    else (
      enter_c2 t)

  and enter_c2 t =
    if G.g2 t.ctx then (
      { t with state = State S3 })
    else (
      { t with state = State S1 })

  let step t signal =
    match t.state, signal with
    | State S1, S ->
          enter_c1 t
    | _ -> t

  let create ctx =
    { state = State S1; ctx }
end|}

let test_inherited_transition () =
  check_output ~msg:"parent transition visible in child leaf"
    (render
       {|
    state machine M {
      signal alarm
      signal tick
      initial enter Running
      state Running {
        on alarm enter Stopped
        initial enter Counting
        state Counting { on tick enter Counting }
      }
      state Stopped
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)
type counting
type stopped

type _ state =
  | Counting : counting state
  | Stopped : stopped state

type any = State : _ state -> any

type signal =
  | Alarm
  | Tick

module Make : sig
  type t
  val create : unit -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any }

  let state t = t.state

  let step t signal =
    match t.state, signal with
    | State Counting, Alarm ->
          { state = State Stopped }
    | State Counting, Tick ->
          { state = State Counting }
    | _ -> t

  let create () =
    { state = State Counting }
end|}

(* ── State machines: type definitions ────────────────────────────── *)

let test_enum_type () =
  check_output ~msg:"enum inside state machine"
    (render
       {|
    state machine M {
      enum Color { RED, GREEN, BLUE }
      signal s
      initial enter S
      state S
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)

type color =
  | Red
  | Green
  | Blue
type s

type _ state =
  | S : s state

type any = State : _ state -> any

type signal =
  | S

module Make : sig
  type t
  val create : unit -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any }

  let state t = t.state

  let step t signal =
    match t.state, signal with
    | _ -> t

  let create () =
    { state = State S }
end|}

let test_struct_type () =
  check_output ~msg:"struct inside state machine"
    (render
       {|
    state machine M {
      struct Point { x: F64, y: F64 }
      signal s
      initial enter S
      state S
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)

type point = {
  x : float;
  y : float;
}
type s

type _ state =
  | S : s state

type any = State : _ state -> any

type signal =
  | S

module Make : sig
  type t
  val create : unit -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any }

  let state t = t.state

  let step t signal =
    match t.state, signal with
    | _ -> t

  let create () =
    { state = State S }
end|}

let test_array_type () =
  check_output ~msg:"array inside state machine"
    (render
       {|
    state machine M {
      array Readings = [10] F64
      signal s
      initial enter S
      state S
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)

type readings = float array
type s

type _ state =
  | S : s state

type any = State : _ state -> any

type signal =
  | S

module Make : sig
  type t
  val create : unit -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any }

  let state t = t.state

  let step t signal =
    match t.state, signal with
    | _ -> t

  let create () =
    { state = State S }
end|}

(* ── State machines: edge cases ──────────────────────────────────── *)

let test_external_sm () =
  check_output ~msg:"bodyless state machine produces nothing"
    (render {| state machine External |})
    ""

let test_catchall_pattern () =
  check_output ~msg:"partial signal coverage emits per-state + final catchall"
    (render
       {|
    state machine M {
      signal a
      signal b
      signal c
      initial enter S1
      state S1 { on a enter S2 }
      state S2
    } |})
    {|(* Generated by ofpp to-ml from state machine M *)
type s1
type s2

type _ state =
  | S1 : s1 state
  | S2 : s2 state

type any = State : _ state -> any

type signal =
  | A
  | B
  | C

module Make : sig
  type t
  val create : unit -> t
  val state : t -> any
  val step : t -> signal -> t
end = struct
  type t = { state : any }

  let state t = t.state

  let step t signal =
    match t.state, signal with
    | State S1, A ->
          { state = State S2 }
    | State S1, _ -> t
    | _ -> t

  let create () =
    { state = State S1 }
end|}

(* ── Topology: default (unannotated) mode ────────────────────────── *)

let test_simple_topology () =
  check_output ~msg:"passive components, inline connect"
    (render_topo
       {|
    port P
    passive component Sensor { output port dataOut: P }
    passive component Logger { sync input port dataIn: P }
    instance sensor: Sensor base id 0x100
    instance logger: Logger base id 0x200
    topology System {
      instance sensor
      instance logger
      connections Data { sensor.dataOut -> logger.dataIn }
    } |})
    {|(* Generated by ofpp to-ml from topology System *)

module type LOGGER = sig
  type t
end

module type SENSOR = sig
  type t
end

module Make
  (Logger : LOGGER)
  (Sensor : sig include SENSOR val connect : Logger.t -> t end) = struct
  type t = { logger : Logger.t; sensor : Sensor.t; }
  let connect logger =
    let sensor = Sensor.connect logger in
    { logger; sensor }
end|}

let test_typed_port_topology () =
  check_output ~msg:"typed ports in default mode"
    (render_topo
       {|
    port DataPort(value: U32) -> bool
    passive component Producer { output port out: DataPort }
    passive component Consumer { sync input port in_: DataPort }
    instance producer: Producer base id 0x100
    instance consumer: Consumer base id 0x200
    topology App {
      instance producer
      instance consumer
      connections Main { producer.out -> consumer.in_ }
    } |})
    {|(* Generated by ofpp to-ml from topology App *)

module type CONSUMER = sig
  type t
end

module type PRODUCER = sig
  type t
end

module Make
  (Consumer : CONSUMER)
  (Producer : sig include PRODUCER val connect : Consumer.t -> t end) = struct
  type t = { consumer : Consumer.t; producer : Producer.t; }
  let connect consumer =
    let producer = Producer.connect consumer in
    { consumer; producer }
end|}

(* ── Topology: annotated (functor-application) mode ──────────────── *)

let test_annotated_topology () =
  check_output ~msg:"functor apps, ocaml.param, Lwt"
    (render_topo
       {|
    port P
    active component Net { sync input port write: P }
    @ ocaml.functor Eth.Make
    active component Ethernet {
      output port net: P
      sync input port write: P
    }
    @ ocaml.functor Ipv4.Make
    active component Ipv4 {
      output port eth: P
      sync input port write: P
      @ ocaml.param
      sync input port cidr: P
    }
    instance net: Net base id 0x100
    instance eth: Ethernet base id 0x200
    instance ipv4: Ipv4 base id 0x300
    topology Stack {
      instance net
      instance eth
      instance ipv4
      connections W {
        eth.net -> net.write
        ipv4.eth -> eth.write
      }
    } |})
    {|(* Generated by ofpp to-ml from topology Stack *)

module Make
  (Net : NET) = struct
  module Eth = Eth.Make(Net)
  module Ipv4 = Ipv4.Make(Eth)

  type t = { net : Net.t; eth : Eth.t; ipv4 : Ipv4.t; }

  let connect ~cidr net =
    let open Lwt.Syntax in
    let* eth = Eth.connect net in
    let* ipv4 = Ipv4.connect ~cidr eth in
    Lwt.return { net; eth; ipv4 }
end|}

let test_annotated_default_functor () =
  check_output ~msg:"ComponentName.Make convention"
    (render_topo
       {|
    port P
    @ ocaml.functor Foo.Make
    active component Foo { output port out: P }
    active component Bar { sync input port in_: P }
    instance foo: Foo base id 0x100
    instance bar: Bar base id 0x200
    topology T {
      instance foo
      instance bar
      connections C { foo.out -> bar.in_ }
    } |})
    {|(* Generated by ofpp to-ml from topology T *)

module Make
  (Bar : BAR) = struct
  module Foo = Foo.Make(Bar)

  type t = { bar : Bar.t; foo : Foo.t; }

  let connect bar =
    let open Lwt.Syntax in
    let* foo = Foo.connect bar in
    Lwt.return { bar; foo }
end|}

let test_functor_param_list () =
  check_output ~msg:"_ placeholders + literal modules"
    (render_topo
       {|
    port P
    active component Net { sync input port write: P }
    @ ocaml.functor Arp.Make(_, Mirage_sleep)
    active component Arp {
      output port eth: P
      sync input port query: P
    }
    instance net: Net base id 0x100
    instance arp: Arp base id 0x200
    topology T {
      instance net
      instance arp
      connections C { arp.eth -> net.write }
    } |})
    {|(* Generated by ofpp to-ml from topology T *)

module Make
  (Net : NET) = struct
  module Arp = Arp.Make(Net)(Mirage_sleep)

  type t = { net : Net.t; arp : Arp.t; }

  let connect net =
    let open Lwt.Syntax in
    let* arp = Arp.connect net in
    Lwt.return { net; arp }
end|}

let test_connect_args () =
  check_output ~msg:"labeled args injected into connect"
    (render_topo
       {|
    port P
    active component V4 { sync input port write: P }
    active component V6 { sync input port write: P }
    @ ocaml.functor IPV4V6
    @ ocaml.connect_args ~ipv4_only:true ~ipv6_only:false
    active component Ip {
      output port v4: P
      output port v6: P
    }
    instance v4: V4 base id 0x100
    instance v6: V6 base id 0x200
    instance ip: Ip base id 0x300
    topology T {
      instance v4
      instance v6
      instance ip
      connections C {
        ip.v4 -> v4.write
        ip.v6 -> v6.write
      }
    } |})
    {|(* Generated by ofpp to-ml from topology T *)

module Make
  (V4 : V4)
  (V6 : V6) = struct
  module Ip = IPV4V6(V4)(V6)

  type t = { v4 : V4.t; v6 : V6.t; ip : Ip.t; }

  let connect v4 v6 =
    let open Lwt.Syntax in
    let* ip = Ip.connect ~ipv4_only:true ~ipv6_only:false v4 v6 in
    Lwt.return { v4; v6; ip }
end|}

let test_topology_import () =
  check_output ~msg:"import merges public instances"
    (render_topo
       {|
    port P
    active component Net { sync input port write: P }
    @ ocaml.functor Eth.Make
    active component Eth {
      output port net: P
      sync input port write: P
    }
    active component Srv { output port eth: P }
    instance net: Net base id 0x100
    instance eth: Eth base id 0x200
    instance srv: Srv base id 0x300
    topology Base {
      instance net
      instance eth
      connections W { eth.net -> net.write }
    }
    topology App {
      import Base
      instance srv
      connections W { srv.eth -> eth.write }
    } |})
    {|(* Generated by ofpp to-ml from topology Base *)

module Make
  (Net : NET) = struct
  module Eth = Eth.Make(Net)

  type t = { net : Net.t; eth : Eth.t; }

  let connect net =
    let open Lwt.Syntax in
    let* eth = Eth.connect net in
    Lwt.return { net; eth }
end
(* Generated by ofpp to-ml from topology App *)

module Make
  (Net : NET) = struct
  module Eth = Eth.Make(Net)
  module Srv = Srv.Make(Eth)

  type t = { net : Net.t; eth : Eth.t; srv : Srv.t; }

  let connect net =
    let open Lwt.Syntax in
    let* eth = Eth.connect net in
    let* srv = Srv.connect eth in
    Lwt.return { net; eth; srv }
end|}

let test_passive_in_annotated () =
  check_output ~msg:"passive gets functor app but no connect/record"
    (render_topo
       {|
    port P
    @ ocaml.functor Crunch.Make
    passive component Kv { output port dep: P }
    active component Http { sync input port static: P }
    instance kv: Kv base id 0x100
    instance http: Http base id 0x200
    topology T {
      instance kv
      instance http
      connections C { kv.dep -> http.static }
    } |})
    {|(* Generated by ofpp to-ml from topology T *)

module Make
  (Http : HTTP) = struct
  module Kv = Crunch.Make(Http)

  type t = { http : Http.t; }

  let connect http =
    { http }
end|}

(* ── Module type generation ──────────────────────────────────────── *)

let test_sig_annotation () =
  check_output ~msg:"ocaml.sig becomes module type alias"
    (render_module_types
       {|
    port P
    @ ocaml.sig Mirage_net.S
    active component Net { sync input port write: P }
    active component Eth {
      output port net: P
      sync input port write: P
    }
    instance net: Net base id 0x100
    instance eth: Eth base id 0x200
    topology T {
      instance net
      instance eth
      connections C { eth.net -> net.write }
    } |})
    {|(* Module types generated by ofpp to-ml *)

module type NET = Mirage_net.S|}

let test_external_types () =
  check_output ~msg:"ocaml.type maps FPP types to OCaml"
    (render_module_types
       {|
    @ ocaml.type Cstruct.t
    type Buffer
    type Macaddr
    port Write(data: Buffer)
    port GetMac -> Macaddr
    active component Net {
      sync input port write: Write
      sync input port mac: GetMac
    }
    active component Eth {
      output port net: Write
      sync input port write: Write
    }
    instance net: Net base id 0x100
    instance eth: Eth base id 0x200
    topology T {
      instance net
      instance eth
      connections C { eth.net -> net.write }
    } |})
    {|(* Module types generated by ofpp to-ml *)

module type NET = sig
  type t
  val write : t -> Cstruct.t -> unit
  val mac : t -> Macaddr.t
end|}

(* ── Suite ───────────────────────────────────────────────────────── *)

let suite =
  ( "gen_ml",
    [
      (* State machines — basic *)
      Alcotest.test_case "simple_sm" `Quick test_simple_sm;
      Alcotest.test_case "typed_signal" `Quick test_typed_signal;
      Alcotest.test_case "guard_choice" `Quick test_guard_choice;
      Alcotest.test_case "nested_state" `Quick test_nested_state;
      Alcotest.test_case "door" `Quick test_door;
      (* State machines — entry/exit, do, typed, inherited *)
      Alcotest.test_case "entry_exit_actions" `Quick test_entry_exit_actions;
      Alcotest.test_case "do_action" `Quick test_do_action;
      Alcotest.test_case "typed_action_guard" `Quick test_typed_action_guard;
      Alcotest.test_case "choice_chain" `Quick test_choice_chain;
      Alcotest.test_case "inherited_transition" `Quick test_inherited_transition;
      (* State machines — type definitions *)
      Alcotest.test_case "enum_type" `Quick test_enum_type;
      Alcotest.test_case "struct_type" `Quick test_struct_type;
      Alcotest.test_case "array_type" `Quick test_array_type;
      (* State machines — edge cases *)
      Alcotest.test_case "external_sm" `Quick test_external_sm;
      Alcotest.test_case "catchall_pattern" `Quick test_catchall_pattern;
      (* Topology — default mode *)
      Alcotest.test_case "simple_topology" `Quick test_simple_topology;
      Alcotest.test_case "typed_port_topology" `Quick test_typed_port_topology;
      (* Topology — annotated mode *)
      Alcotest.test_case "annotated_topology" `Quick test_annotated_topology;
      Alcotest.test_case "annotated_default_functor" `Quick
        test_annotated_default_functor;
      Alcotest.test_case "functor_param_list" `Quick test_functor_param_list;
      Alcotest.test_case "connect_args" `Quick test_connect_args;
      Alcotest.test_case "topology_import" `Quick test_topology_import;
      Alcotest.test_case "passive_in_annotated" `Quick test_passive_in_annotated;
      (* Module types *)
      Alcotest.test_case "sig_annotation" `Quick test_sig_annotation;
      Alcotest.test_case "external_types" `Quick test_external_types;
    ] )
