[@@@ocamlformat "disable"]

module type Ramdisk = Mirage_block.S
(* Generated by ofpp to-ml from topology UnixDiskLottery *)

module Unikernel = Unikernel.Main(Ramdisk)
let unikernel__reset_all =
  let doc = Cmdliner.Arg.info ~doc:"reset_all" ["reset-all"] in
  Mirage_runtime.register_arg Cmdliner.Arg.(value & flag doc)
let unikernel__slot =
  let doc = Cmdliner.Arg.info ~doc:"slot" ["slot"] in
  Mirage_runtime.register_arg Cmdliner.Arg.(value & opt int64 0L doc)
let unikernel__reset =
  let doc = Cmdliner.Arg.info ~doc:"reset" ["reset"] in
  Mirage_runtime.register_arg Cmdliner.Arg.(value & flag doc)

open Lwt.Syntax

let start = lazy (
  let* ramdisk = Ramdisk.connect ~name:"lottery-disk" in
  Unikernel.start ~reset_all:(unikernel__reset_all ()) ~slot:(unikernel__slot ()) ~reset:(unikernel__reset ()) ramdisk)
let mirage_runtime_delay__key = Mirage_runtime.register_arg @@ Mirage_runtime.delay
let mirage_runtime_logs__key = Mirage_runtime.register_arg @@ Mirage_runtime.logs
let cmdliner_stdlib__key = Mirage_runtime.register_arg @@
  Cmdliner_stdlib.setup ~backtrace:(Some true) ~randomize_hashtables:(Some true) ()

let () =
  let t =
    let open Lwt.Syntax in
    let* () = Lwt.return (Mirage_runtime.(with_argv (runtime_args ()) "UnixDiskLottery" (Mirage_bootvar.argv ()))) in
    let _ = cmdliner_stdlib__key () in
    let* () = Mirage_sleep.ns (Duration.of_sec (mirage_runtime_delay__key ())) in
    let reporter = Mirage_logs.create () in
    Mirage_runtime.set_level ~default:(Some Logs.Info) (mirage_runtime_logs__key ());
    Logs.set_reporter reporter;
    let* _ = Mirage_crypto_rng_mirage.initialize (module Mirage_crypto_rng.Fortuna) in
    Mirage_runtime.set_name "UnixDiskLottery";
    let* _ = Lazy.force start in
    Lwt.return ()
  in
  Unix_os.Main.run t; exit 0
