[@@@ocamlformat "disable"]
(* Generated by ofpp to-ml from topology UnixConduit. *)

module Stackv4v6 : sig type t end
module Conduit_tcp : sig end
module Conduit_app : sig end

val connect : Stackv4v6.t Lwt.t Lazy.t

val start : unit Lwt.t Lazy.t
