[@@@ocamlformat "disable"]
(* Generated by ofpp to-ml from topology UnixConduit. *)

module Stackv4v6 : Tcpip.Stack.V4V6
module Conduit_tcp : Conduit_mirage.S
module Conduit_app : sig end

val connect : Stackv4v6.t Lwt.t Lazy.t

val start : unit Lwt.t Lazy.t
