[@@@ocamlformat "disable"]
(* Generated by ofpp to-ml from topology UnixStaticWebsiteTls. *)

module type Udpv4v6_socket = Tcpip.Udp.S
module type Tcpv4v6_socket = Tcpip.Tcp.S
module type Stackv4v6 = Tcpip.Stack.V4V6
module type Static_data = Mirage_kv.RO
module type Tls_keys = Mirage_kv.RO
module Stackv4v6 : Stackv4v6
module Unikernel : sig end

val connect : Stackv4v6.t Lwt.t Lazy.t

val start : unit Lwt.t Lazy.t
