[@@@ocamlformat "disable"]
(* Generated by ofpp to-ml from topology UnixWebsite *)

module Udp_socket = Server.Udp_socket
module Tcp_socket = Server.Tcp_socket
module Socket_stack = Server.Socket_stack
module Data = Htdocs_data
module Certs = Tls_data
module Conduit_tcp = Conduit_mirage.TCP(Socket_stack)
module Conduit = Conduit_mirage.TLS(Conduit_tcp)
module Http = Cohttp_mirage.Server.Make(Conduit)

let udp_socket = lazy (Udp_socket.connect ())
let tcp_socket = lazy (Tcp_socket.connect ())

let socket_stack = lazy (
  let open Lwt.Syntax in
  let* udp_socket = Lazy.force udp_socket in
  let* tcp_socket = Lazy.force tcp_socket in
  Socket_stack.connect udp_socket tcp_socket)

let data = lazy (Data.connect ())
let certs = lazy (Certs.connect ())
let () =
  Lwt_main.run begin
    let open Lwt.Syntax in
    let* _ = Lazy.force udp_socket in
    let* _ = Lazy.force tcp_socket in
    let* _ = Lazy.force socket_stack in
    let* _ = Lazy.force data in
    let* _ = Lazy.force certs in
    Lwt.return ()
  end
