[@@@ocamlformat "disable"]
(* Generated by ofpp to-ml from topology UnixWebsite *)

module Udpv4v6_socket = Server.Udpv4v6_socket
module Tcpv4v6_socket = Server.Tcpv4v6_socket
module Stackv4v6 = Server.Stackv4v6
module Data = Htdocs_data
module Certs = Tls_data
module Dispatch = Server.HTTPS(Data)(Certs)(Stackv4v6)

let udpv4v6_socket = lazy (
  Udpv4v6_socket.connect ~ipv4_only:Server.Runtime.ipv4_only ~ipv6_only:Server.Runtime.ipv6_only ())
let tcpv4v6_socket = lazy (
  Tcpv4v6_socket.connect ~ipv4_only:Server.Runtime.ipv4_only ~ipv6_only:Server.Runtime.ipv6_only ())

let stackv4v6 = lazy (
  let open Lwt.Syntax in
  let* udpv4v6_socket = Lazy.force udpv4v6_socket in
  let* tcpv4v6_socket = Lazy.force tcpv4v6_socket in
  Stackv4v6.connect udpv4v6_socket tcpv4v6_socket)

let data = lazy (Data.connect ())
let certs = lazy (Certs.connect ())

let dispatch = lazy (
  let open Lwt.Syntax in
  let* data = Lazy.force data in
  let* certs = Lazy.force certs in
  let* stackv4v6 = Lazy.force stackv4v6 in
  Dispatch.start data certs stackv4v6)
let () =
  Lwt_main.run begin
    let open Lwt.Syntax in
    let* _ = Lazy.force udpv4v6_socket in
    let* _ = Lazy.force tcpv4v6_socket in
    let* _ = Lazy.force stackv4v6 in
    let* _ = Lazy.force data in
    let* _ = Lazy.force certs in
    let* _ = Lazy.force dispatch in
    Lwt.return ()
  end
