[@@@ocamlformat "disable"]
(* Module types generated by ofpp to-ml *)

module type BACKEND = sig
  type t
  val provide : t -> unit
end

module type UDPV4V6_SOCKET = sig
  type t
  val provide : t -> unit
end

module type TCPV4V6_SOCKET = sig
  type t
  val provide : t -> unit
end

module type HAPPY_EYEBALLS_MIRAGE = sig
  type t
  val provide : t -> unit
end

module type KV = sig
  type t
  type error
  type key
  val disconnect : t -> unit Lwt.t
  val get : t -> key -> (string, error) result Lwt.t
  val exists : t -> key -> (bool option, error) result Lwt.t
  val list : t -> key -> (string list, error) result Lwt.t
  val digest : t -> key -> (string, error) result Lwt.t
end

module type BLOCK = sig
  type t
  val provide : t -> unit
end
