[@@@ocamlformat "disable"]
(* Module types generated by ofpp to-ml *)

module type BACKEND = sig
  type t
  val write : t -> Cstruct.t -> unit
  val listen : t -> int32 -> unit
  val mac : t -> Macaddr.t
  val mtu : t -> int32
  val disconnect : t -> unit Lwt.t
end

module type UDPV4V6_SOCKET = sig
  type t
  val disconnect : t -> unit Lwt.t
end

module type TCPV4V6_SOCKET = sig
  type t
  val disconnect : t -> unit Lwt.t
end

module type HAPPY_EYEBALLS_MIRAGE = sig
  type t
  val disconnect : t -> unit Lwt.t
end
