[@@@ocamlformat "disable"]
(* Module types generated by ofpp to-ml *)

module type BACKEND = sig
  type t
  val provide : t -> unit
end

module type CONDUIT_TCP = sig
  type t
  val connect : t -> unit
end

module type UDPV4V6_SOCKET = sig
  type t
  val provide : t -> unit
end

module type TCPV4V6_SOCKET = sig
  type t
  val provide : t -> unit
end

module type HAPPY_EYEBALLS_MIRAGE = sig
  type t
  val provide : t -> unit
end
