[@@@ocamlformat "disable"]
(* Module types generated by ofpp to-ml *)

module type BACKEND = sig
  type t
  val write : t -> Cstruct.t -> unit
  val listen : t -> int32 -> unit
  val mac : t -> Macaddr.t
  val mtu : t -> int32
  val disconnect : t -> unit Lwt.t
end

module type KV = sig
  type t
  type error
  type key
  val disconnect : t -> unit Lwt.t
  val get : t -> key -> (string, error) result Lwt.t
  val exists : t -> key -> (bool option, error) result Lwt.t
  val list : t -> key -> (string list, error) result Lwt.t
  val digest : t -> key -> (string, error) result Lwt.t
end

module type BLOCK = sig
  type t
  type error
  type write_error
  val disconnect : t -> unit Lwt.t
  val get_info : t -> Mirage_block.info Lwt.t
  val read : t -> int64 -> Cstruct.t -> (unit, error) result Lwt.t
  val write : t -> int64 -> Cstruct.t -> (unit, write_error) result Lwt.t
end
