[@@@ocamlformat "disable"]
(* Module types generated by ofpp to-ml *)

module type BACKEND = sig
  type t
  val provide : t -> unit
end

module type KV = sig
  type t
  val disconnect : t -> unit
  val get : t -> string -> string
  val exists : t -> string -> bool
  val list : t -> string -> string
  val digest : t -> string -> string
end

module type BLOCK = sig
  type t
  val provide : t -> unit
end
