[@@@ocamlformat "disable"]
(* Generated by ofpp to-ml from topology UnixHttp. *)

module type Udpv4v6_socket = Tcpip.Udp.S
module type Tcpv4v6_socket = Tcpip.Tcp.S
module type Stackv4v6 = Tcpip.Stack.V4V6
module type Happy_eyeballs_mirage = Happy_eyeballs_mirage.S
module type Dns_client = Dns_client_mirage.S
module type Certs_data = Mirage_kv.RO
module type Keys_data = Mirage_kv.RO
module type Paf_server = Paf_mirage.S
module Stackv4v6 : Stackv4v6
module Happy_eyeballs_mirage : Happy_eyeballs_mirage
module Dns_client : Dns_client
module Paf_server : Paf_server
module Unikernel : sig end

val connect : Stackv4v6.t Lwt.t Lazy.t

val connect_device : (Stackv4v6.t * Happy_eyeballs_mirage.t) Lwt.t Lazy.t

val start : unit Lwt.t Lazy.t
