[@@@ocamlformat "disable"]

module type Udpv4v6_socket = Tcpip.Udp.S
module type Tcpv4v6_socket = Tcpip.Tcp.S
module type Certs_data = Mirage_kv.RO
module type Keys_data = Mirage_kv.RO
module type Http_server = Paf_mirage.S
module type Stackv4v6 = Tcpip.Stack.V4V6
module type Happy_eyeballs_mirage = Happy_eyeballs_mirage.S
module type Dns_client = Dns_client_mirage.S
(* Generated by ofpp to-ml from topology UnixHttp *)
let unikernel__alpn = Mirage_runtime.register_arg @@ Unikernel.alpn

module Http_server = Paf_mirage.Make(Tcpv4v6_socket)
module Stackv4v6 = Stackv4v6.Make(Udpv4v6_socket)(Tcpv4v6_socket)
module Happy_eyeballs_mirage = Happy_eyeballs_mirage.Make(Stackv4v6)
module Dns_client = Dns_resolver.Make(Stackv4v6)(Happy_eyeballs_mirage)
module Mimic_happy_eyeballs = Mimic_happy_eyeballs.Make(Stackv4v6)(Happy_eyeballs_mirage)
module Connect = Connect.Make(Tcpv4v6_socket)(Mimic_happy_eyeballs)
module Unikernel = Unikernel.Make(Certs_data)(Keys_data)(Tcpv4v6_socket)(Connect)(Http_server)
let unikernel__tls =
  let doc = Cmdliner.Arg.info ~doc:"tls" ["tls"] in
  Mirage_runtime.register_arg Cmdliner.Arg.(value & flag doc)
let unikernel__tls_port =
  let doc = Cmdliner.Arg.info ~doc:"tls_port" ["tls-port"] in
  Mirage_runtime.register_arg Cmdliner.Arg.(value & opt int 4343 doc)

open Lwt.Syntax

let connect = lazy (
  let* udpv4v6_socket = Udpv4v6_socket.connect ~ipv4_only:false ~ipv6_only:false (Ipaddr.V4.Prefix.of_string_exn "0.0.0.0/0") None in
  let* tcpv4v6_socket = Tcpv4v6_socket.connect ~ipv4_only:false ~ipv6_only:false (Ipaddr.V4.Prefix.of_string_exn "0.0.0.0/0") None in
  let* stackv4v6 = Stackv4v6.connect udpv4v6_socket tcpv4v6_socket in
  Lwt.return (tcpv4v6_socket, stackv4v6))

let connect_device = lazy (
  let* (tcpv4v6_socket, stackv4v6) = Lazy.force connect in
  let* happy_eyeballs_mirage = Happy_eyeballs_mirage.connect_device stackv4v6 in
  Lwt.return (tcpv4v6_socket, stackv4v6, happy_eyeballs_mirage))

let start = lazy (
  let* (tcpv4v6_socket, stackv4v6, happy_eyeballs_mirage) = Lazy.force connect_device in
  let* certs_data = Certs_data.connect () in
  let* keys_data = Keys_data.connect () in
  let* http_server = Http_server.init ~port:8080 tcpv4v6_socket in
  let* _dns_client = Dns_client.start stackv4v6 happy_eyeballs_mirage in
  let* mimic_happy_eyeballs = Mimic_happy_eyeballs.connect happy_eyeballs_mirage in
  let* connect = Connect.connect mimic_happy_eyeballs in
  Unikernel.start ~tls:(unikernel__tls ()) ~tls_port:(unikernel__tls_port ()) ~alpn:(unikernel__alpn ()) certs_data keys_data tcpv4v6_socket connect http_server)
let mirage_runtime_delay__key = Mirage_runtime.register_arg @@ Mirage_runtime.delay
let mirage_runtime_logs__key = Mirage_runtime.register_arg @@ Mirage_runtime.logs
let cmdliner_stdlib__key = Mirage_runtime.register_arg @@
  Cmdliner_stdlib.setup ~backtrace:(Some true) ~randomize_hashtables:(Some true) ()

let () =
  let t =
    let open Lwt.Syntax in
    let* () = Lwt.return (Mirage_runtime.(with_argv (runtime_args ()) "UnixHttp" (Mirage_bootvar.argv ()))) in
    let _ = cmdliner_stdlib__key () in
    let* () = Mirage_sleep.ns (Duration.of_sec (mirage_runtime_delay__key ())) in
    let reporter = Mirage_logs.create () in
    Mirage_runtime.set_level ~default:(Some Logs.Info) (mirage_runtime_logs__key ());
    Logs.set_reporter reporter;
    let* _ = Mirage_crypto_rng_mirage.initialize (module Mirage_crypto_rng.Fortuna) in
    Mirage_runtime.set_name "UnixHttp";
    let* _ = Lazy.force start in
    Lwt.return ()
  in
  Unix_os.Main.run t; exit 0
