[@@@ocamlformat "disable"]
(* Generated by ofpp to-ml from topology UnixDns. *)

module Stackv4v6 : Tcpip.Stack.V4V6
module Happy_eyeballs_mirage : Happy_eyeballs_mirage.S
module Dns_client : Dns_client_mirage.S
module App : sig end

val connect : Stackv4v6.t Lwt.t Lazy.t

val connect_device : (Stackv4v6.t * Happy_eyeballs_mirage.t) Lwt.t Lazy.t

val start : unit Lwt.t Lazy.t
