[@@@ocamlformat "disable"]
(* Generated by ofpp to-ml from topology UnixDns. *)

module Stackv4v6 : sig type t end
module Happy_eyeballs_mirage : sig type t end
module Dns_client : sig end
module Dns_client_app : sig end

val connect : Stackv4v6.t Lwt.t Lazy.t

val connect_device : (Stackv4v6.t * Happy_eyeballs_mirage.t) Lwt.t Lazy.t

val start : unit Lwt.t Lazy.t
