[@@@ocamlformat "disable"]

module type Netif = Mirage_net.S
module type Ethernet = Ethernet.S
module type Ipv6 = Tcpip.Ip.S
(* Generated by ofpp to-ml from topology Solo5Ping6 *)

module Ethernet = Ethernet.Make(Netif)
module Ipv6 = Ipv6.Make(Netif)(Ethernet)
module Unikernel = Unikernel.Main(Netif)(Ethernet)(Ipv6)

open Lwt.Syntax

let connect = lazy (
  let* netif = Netif.connect "service" in
  let* ethernet = Ethernet.connect netif in
  let* ipv6 = Ipv6.connect netif ethernet in
  Lwt.return (netif, ethernet, ipv6))

let start = lazy (
  let* (netif, ethernet, ipv6) = Lazy.force connect in
  Unikernel.start netif ethernet ipv6)
let mirage_runtime_delay__key = Mirage_runtime.register_arg @@ Mirage_runtime.delay
let mirage_runtime_logs__key = Mirage_runtime.register_arg @@ Mirage_runtime.logs
let cmdliner_stdlib__key = Mirage_runtime.register_arg @@
  Cmdliner_stdlib.setup ~backtrace:(Some true) ~randomize_hashtables:(Some true) ()

let () =
  let t =
    let open Lwt.Syntax in
    let* () = Lwt.return (Mirage_runtime.(with_argv (runtime_args ()) "Solo5Ping6" (Mirage_bootvar.argv ()))) in
    let _ = cmdliner_stdlib__key () in
    let* () = Mirage_sleep.ns (Duration.of_sec (mirage_runtime_delay__key ())) in
    let reporter = Mirage_logs.create () in
    Mirage_runtime.set_level ~default:(Some Logs.Info) (mirage_runtime_logs__key ());
    Logs.set_reporter reporter;
    let* _ = Mirage_crypto_rng_mirage.initialize (module Mirage_crypto_rng.Fortuna) in
    Mirage_runtime.set_name "Solo5Ping6";
    let* _ = Lazy.force start in
    Lwt.return ()
  in
  Solo5_os.Main.run t; exit 0
