[@@@ocamlformat "disable"]
(* Generated by ofpp to-ml from topology Solo5Ping6. *)

module type Netif = Mirage_net.S
module type Ethernet = Ethernet.S
module type Ipv6 = Tcpip.Ip.S
module Ethernet : Ethernet
module Ipv6 : Ipv6
module Unikernel : sig end

val connect : (Netif.t * Ethernet.t * Ipv6.t) Lwt.t Lazy.t

val start : unit Lwt.t Lazy.t
