[@@@ocamlformat "disable"]
(* Generated by ofpp to-ml from topology UnixPing6. *)

module Ethernet : Ethernet.S
module Ipv6 : Tcpip.Ip.S
module Unikernel : sig end

val connect : (Netif.t * Ethernet.t * Ipv6.t) Lwt.t Lazy.t

val start : unit Lwt.t Lazy.t
