Basic state machine (phantom-typed GADT)
  $ cat > simple.fpp <<EOF
  > state machine M {
  >   signal s
  >   initial enter S1
  >   state S1 { on s enter S2 }
  >   state S2
  > }
  > EOF
  $ ofpp to-ml simple.fpp
  (* Generated by ofpp to-ml from state machine M *)
  type s1
  type s2
  
  type _ state =
    | S1 : s1 state
    | S2 : s2 state
  
  type any = State : _ state -> any
  
  type signal =
    | S
  
  module Make : sig
    type t
    val create : unit -> t
    val state : t -> any
    val step : t -> signal -> t
  end = struct
    type t = { state : any }
  
    let state t = t.state
  
    let step t signal =
      match t.state, signal with
      | State S1, S ->
          { state = State S2 }
      | _ -> t
  
    let create () =
      { state = State S1 }
  end

Door example (guards, actions, signals)
  $ cat > door.fpp <<EOF
  > state machine Door {
  >   action lock
  >   guard locked
  >   signal open
  >   signal close
  >   initial enter Closed
  >   state Closed { on open if locked enter Closed
  >                  on open enter Opened }
  >   state Opened { on close do { lock } enter Closed }
  > }
  > EOF
  $ ofpp to-ml door.fpp
  (* Generated by ofpp to-ml from state machine Door *)
  type closed
  type opened
  
  type _ state =
    | Closed : closed state
    | Opened : opened state
  
  type any = State : _ state -> any
  
  type signal =
    | Open
    | Close
  
  module type ACTIONS = sig
    type ctx
    val lock : ctx -> unit
  end
  
  module type GUARDS = sig
    type ctx
    val locked : ctx -> bool
  end
  
  module Make (A : ACTIONS) (G : GUARDS with type ctx = A.ctx) : sig
    type t
    val create : A.ctx -> t
    val state : t -> any
    val step : t -> signal -> t
  end = struct
    type t = { state : any; ctx : A.ctx }
  
    let state t = t.state
  
    let step t signal =
      match t.state, signal with
      | State Closed, Open ->
          if G.locked t.ctx then begin
          { t with state = State Closed }
          end
          else begin
          { t with state = State Opened }
          end
      | State Closed, _ -> t
      | State Opened, Close ->
          A.lock t.ctx;
          { t with state = State Closed }
      | State Opened, _ -> t
  
    let create ctx =
      { state = State Closed; ctx }
  end

Type definitions (enum, struct, array, abstract type)
  $ cat > types.fpp <<EOF
  > state machine SM {
  >   enum E { X, Y }
  >   struct S { x: U32, y: E }
  >   array A = [3] U32
  >   type T
  >   initial enter S1
  >   state S1
  > }
  > EOF
  $ ofpp to-ml types.fpp
  (* Generated by ofpp to-ml from state machine SM *)
  
  type e =
    | X
    | Y
  
  type s = {
    x : int32;
    y : e;
  }
  
  type a = int32 array
  type s1
  
  type _ state =
    | S1 : s1 state
  
  type any = State : _ state -> any
  
  module Make : sig
    type t
    val create : unit -> t
    val state : t -> any
  end = struct
    type t = { state : any }
  
    let state t = t.state
  
    let create () =
      { state = State S1 }
  end

External state machine produces no output
  $ cat > ext.fpp <<EOF
  > state machine M
  > EOF
  $ ofpp to-ml ext.fpp

Simple topology (2 components, 1 connection)
  $ cat > topo.fpp <<EOF
  > port P
  > passive component Sensor {
  >   output port dataOut: P
  > }
  > passive component Logger {
  >   sync input port dataIn: P
  > }
  > instance sensor: Sensor base id 0x100
  > instance logger: Logger base id 0x200
  > topology System {
  >   instance sensor
  >   instance logger
  >   connections Data {
  >     sensor.dataOut -> logger.dataIn
  >   }
  > }
  > EOF
  $ ofpp to-ml topo.fpp
  (* Generated by ofpp to-ml from topology System *)
  
  module type LOGGER = sig
    type t
  end
  
  module type SENSOR = sig
    type t
  end
  
  module Make
    (Logger : LOGGER)
    (Sensor : sig include SENSOR val connect : Logger.t -> t end) = struct
    type t = { logger : Logger.t; sensor : Sensor.t; }
    let data logger =
      let sensor = Sensor.connect logger in
      { logger; sensor }
  end











Typed port topology
  $ cat > typed_topo.fpp <<EOF
  > port DataPort(value: U32) -> bool
  > passive component Producer {
  >   output port out: DataPort
  > }
  > passive component Consumer {
  >   sync input port in_: DataPort
  > }
  > instance producer: Producer base id 0x100
  > instance consumer: Consumer base id 0x200
  > topology App {
  >   instance producer
  >   instance consumer
  >   connections Main {
  >     producer.out -> consumer.in_
  >   }
  > }
  > EOF
  $ ofpp to-ml typed_topo.fpp
  (* Generated by ofpp to-ml from topology App *)
  
  module type CONSUMER = sig
    type t
  end
  
  module type PRODUCER = sig
    type t
  end
  
  module Make
    (Consumer : CONSUMER)
    (Producer : sig include PRODUCER val connect : Consumer.t -> t end) = struct
    type t = { consumer : Consumer.t; producer : Producer.t; }
    let main consumer =
      let producer = Producer.connect consumer in
      { consumer; producer }
  end











Filter by topology name
  $ cat > multi_topo.fpp <<EOF
  > port P
  > passive component A { output port out: P }
  > passive component B { sync input port in_: P }
  > instance a: A base id 0x100
  > instance b: B base id 0x200
  > topology T1 {
  >   instance a
  >   instance b
  >   connections C { a.out -> b.in_ }
  > }
  > topology T2 {
  >   instance a
  >   instance b
  >   connections C { a.out -> b.in_ }
  > }
  > EOF
  $ ofpp to-ml --topology T2 multi_topo.fpp
  (* Generated by ofpp to-ml from topology T2 *)
  
  module type B = sig
    type t
  end
  
  module type A = sig
    type t
  end
  
  module Make
    (B : B)
    (A : sig include A val connect : B.t -> t end) = struct
    type t = { b : B.t; a : A.t; }
    let c b =
      let a = A.connect b in
      { b; a }
  end











SM + topology merged in one file (wrapped in named modules)
  $ cat > merged.fpp <<EOF
  > state machine M {
  >   initial enter S
  >   state S
  > }
  > port P
  > passive component Sensor { output port dataOut: P }
  > passive component Logger { sync input port dataIn: P }
  > instance sensor: Sensor base id 0x100
  > instance logger: Logger base id 0x200
  > topology System {
  >   instance sensor
  >   instance logger
  >   connections Data { sensor.dataOut -> logger.dataIn }
  > }
  > EOF
  $ ofpp to-ml merged.fpp
  module M = struct
  (* Generated by ofpp to-ml from state machine M *)
  type s
  
  type _ state =
    | S : s state
  
  type any = State : _ state -> any
  
  module Make : sig
    type t
    val create : unit -> t
    val state : t -> any
  end = struct
    type t = { state : any }
  
    let state t = t.state
  
    let create () =
      { state = State S }
  end
  end
  module System = struct
  (* Generated by ofpp to-ml from topology System *)
  
  module type LOGGER = sig
    type t
  end
  
  module type SENSOR = sig
    type t
  end
  
  module Make
    (Logger : LOGGER)
    (Sensor : sig include SENSOR val connect : Logger.t -> t end) = struct
    type t = { logger : Logger.t; sensor : Sensor.t; }
    let data logger =
      let sensor = Sensor.connect logger in
      { logger; sensor }
  end
  end
















Filter by SM name
  $ cat > multi.fpp <<EOF
  > state machine A {
  >   initial enter S
  >   state S
  > }
  > state machine B {
  >   initial enter T
  >   state T
  > }
  > EOF
  $ ofpp to-ml --sm B multi.fpp
  (* Generated by ofpp to-ml from state machine B *)
  type t
  
  type _ state =
    | T : t state
  
  type any = State : _ state -> any
  
  module Make : sig
    type t
    val create : unit -> t
    val state : t -> any
  end = struct
    type t = { state : any }
  
    let state t = t.state
  
    let create () =
      { state = State T }
  end






Annotated topology (functor-application mode)
  $ cat > annot_topo.fpp <<EOF
  > port P
  > active component Net { sync input port write: P }
  > active component Eth {
  >   output port net: P
  >   sync input port write: P
  > }
  > active component Ipv4 {
  >   output port eth: P
  >   @ ocaml.param
  >   sync input port cidr: P
  > }
  > instance net: Net base id 0x100
  > instance eth: Eth base id 0x200
  > instance ipv4: Ipv4 base id 0x300
  > topology Stack {
  >   instance net
  >   instance eth
  >   instance ipv4
  >   connections W {
  >     eth.net -> net.write
  >     ipv4.eth -> eth.write
  >   }
  > }
  > EOF
  $ ofpp to-ml annot_topo.fpp
  (* Module types generated by ofpp to-ml *)
  
  module type NET = sig
    type t
    val write : t -> unit
  end
  
  (* Generated by ofpp to-ml from topology Stack *)
  
  module Make
    (Net : NET) = struct
    module Eth = Eth.Make(Net)
    module Ipv4 = Ipv4.Make(Eth)
  
    type t = { net : Net.t; eth : Eth.t; ipv4 : Ipv4.t; }
  
    let w ~cidr net =
      let open Lwt.Syntax in
      let* eth = Eth.connect net in
      let* ipv4 = Ipv4.connect ~cidr eth in
      Lwt.return { net; eth; ipv4 }
  end

Bound leaf instance (@ ocaml.module)
  $ ofpp to-ml data/bound-leaf.fpp
  (* Generated by ofpp to-ml from topology T *)
  
  module Make = struct
    module Kv = Embedded_data
    module Srv = Srv.Make(Kv)
  
    type t = { kv : Kv.t; srv : Srv.t; }
  
    let w () =
      let open Lwt.Syntax in
      let* kv = Kv.connect () in
      let* srv = Srv.connect kv in
      Lwt.return { kv; srv }
  end




External types in port declarations
  $ cat > ext_types.fpp <<EOF
  > @ ocaml.type Cstruct.t
  > type Buffer
  > type Macaddr
  > port Write(data: Buffer)
  > port GetMac -> Macaddr
  > active component Net {
  >   sync input port write: Write
  >   sync input port mac: GetMac
  > }
  > active component Eth {
  >   output port net: Write
  >   sync input port write: Write
  > }
  > instance net: Net base id 0x100
  > instance eth: Eth base id 0x200
  > topology T {
  >   instance net
  >   instance eth
  >   connections C { eth.net -> net.write }
  > }
  > EOF
  $ ofpp to-ml ext_types.fpp
  (* Module types generated by ofpp to-ml *)
  
  module type NET = sig
    type t
    val write : t -> Cstruct.t -> unit
    val mac : t -> Macaddr.t
  end
  
  (* Generated by ofpp to-ml from topology T *)
  
  module Make
    (Net : NET) = struct
    module Eth = Eth.Make(Net)
  
    type t = { net : Net.t; eth : Eth.t; }
  
    let c net =
      let open Lwt.Syntax in
      let* eth = Eth.connect net in
      Lwt.return { net; eth }
  end





