Basic state machine (phantom-typed GADT)
  $ cat > simple.fpp <<EOF
  > state machine M {
  >   signal s
  >   initial enter S1
  >   state S1 { on s enter S2 }
  >   state S2
  > }
  > EOF
  $ ofpp to-ml simple.fpp
  (* Generated by ofpp to-ml from state machine M *)
  type s1
  type s2
  
  type _ state =
    | S1 : s1 state
    | S2 : s2 state
  
  type any = State : _ state -> any
  
  type signal =
    | S
  
  module Make : sig
    type t
    val create : unit -> t
    val state : t -> any
    val step : t -> signal -> t
  end = struct
    type t = { state : any }
  
    let state t = t.state
  
    let step t signal =
      match t.state, signal with
      | State S1, S ->
            { state = State S2 }
      | _ -> t
  
    let create () =
      { state = State S1 }
  end

Door example (guards, actions, signals)
  $ cat > door.fpp <<EOF
  > state machine Door {
  >   action lock
  >   guard locked
  >   signal open
  >   signal close
  >   initial enter Closed
  >   state Closed { on open if locked enter Closed
  >                  on open enter Opened }
  >   state Opened { on close do { lock } enter Closed }
  > }
  > EOF
  $ ofpp to-ml door.fpp
  (* Generated by ofpp to-ml from state machine Door *)
  type closed
  type opened
  
  type _ state =
    | Closed : closed state
    | Opened : opened state
  
  type any = State : _ state -> any
  
  type signal =
    | Open
    | Close
  
  module type ACTIONS = sig
    type ctx
    val lock : ctx -> unit
  end
  
  module type GUARDS = sig
    type ctx
    val locked : ctx -> bool
  end
  
  module Make (A : ACTIONS) (G : GUARDS with type ctx = A.ctx) : sig
    type t
    val create : A.ctx -> t
    val state : t -> any
    val step : t -> signal -> t
  end = struct
    type t = { state : any; ctx : A.ctx }
  
    let state t = t.state
  
    let step t signal =
      match t.state, signal with
      | State Closed, Open ->
          if G.locked t.ctx then
            { t with state = State Closed }
          else
            { t with state = State Opened }
      | State Closed, _ -> t
      | State Opened, Close ->
            A.lock t.ctx;
            { t with state = State Closed }
      | State Opened, _ -> t
  
    let create ctx =
      { state = State Closed; ctx }
  end

External state machine produces no output
  $ cat > ext.fpp <<EOF
  > state machine M
  > EOF
  $ ofpp to-ml ext.fpp

Filter by SM name
  $ cat > multi.fpp <<EOF
  > state machine A {
  >   initial enter S
  >   state S
  > }
  > state machine B {
  >   initial enter T
  >   state T
  > }
  > EOF
  $ ofpp to-ml --sm B multi.fpp
  (* Generated by ofpp to-ml from state machine B *)
  type t
  
  type _ state =
    | T : t state
  
  type any = State : _ state -> any
  
  module Make : sig
    type t
    val create : unit -> t
    val state : t -> any
  end = struct
    type t = { state : any }
  
    let state t = t.state
  
    let create () =
      { state = State T }
  end

