Basic state machine (phantom-typed GADT)
  $ cat > simple.fpp <<EOF
  > state machine M {
  >   signal s
  >   initial enter S1
  >   state S1 { on s enter S2 }
  >   state S2
  > }
  > EOF
  $ ofpp to-ml simple.fpp
  [@@@ocamlformat "disable"]
  (* Generated by ofpp to-ml from state machine M *)
  type s1
  type s2
  
  type _ state =
    | S1 : s1 state
    | S2 : s2 state
  
  type any = State : _ state -> any
  
  type signal =
    | S
  
  module Make : sig
    type t
    val create : unit -> t
    val state : t -> any
    val step : t -> signal -> t
  end = struct
    type t = { state : any }
  
    let state t = t.state
  
    let step t signal =
      match t.state, signal with
      | State S1, S ->
          { state = State S2 }
      | _ -> t
  
    let create () =
      { state = State S1 }
  end

Door example (guards, actions, signals)
  $ cat > door.fpp <<EOF
  > state machine Door {
  >   action lock
  >   guard locked
  >   signal open
  >   signal close
  >   initial enter Closed
  >   state Closed { on open if locked enter Closed
  >                  on open enter Opened }
  >   state Opened { on close do { lock } enter Closed }
  > }
  > EOF
  $ ofpp to-ml door.fpp
  [@@@ocamlformat "disable"]
  (* Generated by ofpp to-ml from state machine Door *)
  type closed
  type opened
  
  type _ state =
    | Closed : closed state
    | Opened : opened state
  
  type any = State : _ state -> any
  
  type signal =
    | Open
    | Close
  
  module type ACTIONS = sig
    type ctx
    val lock : ctx -> unit
  end
  
  module type GUARDS = sig
    type ctx
    val locked : ctx -> bool
  end
  
  module Make (A : ACTIONS) (G : GUARDS with type ctx = A.ctx) : sig
    type t
    val create : A.ctx -> t
    val state : t -> any
    val step : t -> signal -> t
  end = struct
    type t = { state : any; ctx : A.ctx }
  
    let state t = t.state
  
    let step t signal =
      match t.state, signal with
      | State Closed, Open ->
          if G.locked t.ctx then begin
          { t with state = State Closed }
          end
          else begin
          { t with state = State Opened }
          end
      | State Closed, _ -> t
      | State Opened, Close ->
          A.lock t.ctx;
          { t with state = State Closed }
      | State Opened, _ -> t
  
    let create ctx =
      { state = State Closed; ctx }
  end

Type definitions (enum, struct, array, abstract type)
  $ cat > types.fpp <<EOF
  > state machine SM {
  >   enum E { X, Y }
  >   struct S { x: U32, y: E }
  >   array A = [3] U32
  >   type T
  >   initial enter S1
  >   state S1
  > }
  > EOF
  $ ofpp to-ml types.fpp
  [@@@ocamlformat "disable"]
  (* Generated by ofpp to-ml from state machine SM *)
  
  type e =
    | X
    | Y
  
  type s = {
    x : int32;
    y : e;
  }
  
  type a = int32 array
  type s1
  
  type _ state =
    | S1 : s1 state
  
  type any = State : _ state -> any
  
  module Make : sig
    type t
    val create : unit -> t
    val state : t -> any
  end = struct
    type t = { state : any }
  
    let state t = t.state
  
    let create () =
      { state = State S1 }
  end

External state machine produces no output
  $ cat > ext.fpp <<EOF
  > state machine M
  > EOF
  $ ofpp to-ml ext.fpp
  [@@@ocamlformat "disable"]

Simple topology (2 components, 1 connection)
  $ cat > topo.fpp <<EOF
  > port P
  > passive component Sensor {
  >   output port dataOut: P
  > }
  > passive component Logger {
  >   sync input port dataIn: P
  > }
  > instance sensor: Sensor base id 0x100
  > instance logger: Logger base id 0x200
  > topology System {
  >   instance sensor
  >   instance logger
  >   connections Data {
  >     sensor.dataOut -> logger.dataIn
  >   }
  > }
  > EOF
  $ ofpp to-ml topo.fpp
  [@@@ocamlformat "disable"]
  (* Generated by ofpp to-ml from topology System *)
  
  module Sensor = Sensor.Make(Logger)
  
  let data = lazy (
    let open Lwt.Syntax in
    let* logger = Logger.data_in () in
    Sensor.connect logger)













Typed port topology
  $ cat > typed_topo.fpp <<EOF
  > port DataPort(value: U32) -> bool
  > passive component Producer {
  >   output port out: DataPort
  > }
  > passive component Consumer {
  >   sync input port in_: DataPort
  > }
  > instance producer: Producer base id 0x100
  > instance consumer: Consumer base id 0x200
  > topology App {
  >   instance producer
  >   instance consumer
  >   connections Main {
  >     producer.out -> consumer.in_
  >   }
  > }
  > EOF
  $ ofpp to-ml typed_topo.fpp
  [@@@ocamlformat "disable"]
  (* Generated by ofpp to-ml from topology App *)
  
  module Producer = Producer.Make(Consumer)
  
  let main = lazy (
    let open Lwt.Syntax in
    let* consumer = Consumer.in_ () in
    Producer.connect consumer)













Filter by topology name
  $ cat > multi_topo.fpp <<EOF
  > port P
  > passive component A { output port out: P }
  > passive component B { sync input port in_: P }
  > instance a: A base id 0x100
  > instance b: B base id 0x200
  > topology T1 {
  >   instance a
  >   instance b
  >   connections C { a.out -> b.in_ }
  > }
  > topology T2 {
  >   instance a
  >   instance b
  >   connections C { a.out -> b.in_ }
  > }
  > EOF
  $ ofpp to-ml --topologies T2 multi_topo.fpp
  [@@@ocamlformat "disable"]
  (* Generated by ofpp to-ml from topology T2 *)
  
  module A = A.Make(B)
  
  let c = lazy (
    let open Lwt.Syntax in
    let* b = B.in_ () in
    A.connect b)
  let mirage_runtime_delay__key = Mirage_runtime.register_arg @@ Mirage_runtime.delay
  let mirage_runtime_logs__key = Mirage_runtime.register_arg @@ Mirage_runtime.logs
  let cmdliner_stdlib__key = Mirage_runtime.register_arg @@
    Cmdliner_stdlib.setup ~backtrace:(Some true) ~randomize_hashtables:(Some true) ()
  
  let () =
    let t =
      let open Lwt.Syntax in
      let* () = Lwt.return (Mirage_runtime.(with_argv (runtime_args ()) "T2" (Mirage_bootvar.argv ()))) in
      let _ = cmdliner_stdlib__key () in
      let* () = Mirage_sleep.ns (Duration.of_sec (mirage_runtime_delay__key ())) in
      let reporter = Mirage_logs.create () in
      Mirage_runtime.set_level ~default:(Some Logs.Info) (mirage_runtime_logs__key ());
      Logs.set_reporter reporter;
      let* _ = Mirage_crypto_rng_mirage.initialize (module Mirage_crypto_rng.Fortuna) in
      Mirage_runtime.set_name "T2";
      let* _ = Lazy.force c in
      Lwt.return ()
    in
    Unix_os.Main.run t; exit 0













SM + topology merged in one file (wrapped in named modules)
  $ cat > merged.fpp <<EOF
  > state machine M {
  >   initial enter S
  >   state S
  > }
  > port P
  > passive component Sensor { output port dataOut: P }
  > passive component Logger { sync input port dataIn: P }
  > instance sensor: Sensor base id 0x100
  > instance logger: Logger base id 0x200
  > topology System {
  >   instance sensor
  >   instance logger
  >   connections Data { sensor.dataOut -> logger.dataIn }
  > }
  > EOF
  $ ofpp to-ml merged.fpp
  [@@@ocamlformat "disable"]
  module M = struct
  (* Generated by ofpp to-ml from state machine M *)
  type s
  
  type _ state =
    | S : s state
  
  type any = State : _ state -> any
  
  module Make : sig
    type t
    val create : unit -> t
    val state : t -> any
  end = struct
    type t = { state : any }
  
    let state t = t.state
  
    let create () =
      { state = State S }
  end
  end
  module System = struct
  (* Generated by ofpp to-ml from topology System *)
  
  module Sensor = Sensor.Make(Logger)
  
  let data = lazy (
    let open Lwt.Syntax in
    let* logger = Logger.data_in () in
    Sensor.connect logger)
  end


















Filter by SM name
  $ cat > multi.fpp <<EOF
  > state machine A {
  >   initial enter S
  >   state S
  > }
  > state machine B {
  >   initial enter T
  >   state T
  > }
  > EOF
  $ ofpp to-ml --sm B multi.fpp
  [@@@ocamlformat "disable"]
  (* Generated by ofpp to-ml from state machine B *)
  type t
  
  type _ state =
    | T : t state
  
  type any = State : _ state -> any
  
  module Make : sig
    type t
    val create : unit -> t
    val state : t -> any
  end = struct
    type t = { state : any }
  
    let state t = t.state
  
    let create () =
      { state = State T }
  end






Annotated topology (functor-application mode)
  $ cat > annot_topo.fpp <<EOF
  > port P
  > active component Net { sync input port write: P }
  > active component Eth {
  >   output port net: P
  >   sync input port write: P
  > }
  > active component Ipv4 {
  >   output port eth: P
  >   sync input port cidr: P
  > }
  > instance net: Net base id 0x100
  > instance eth: Eth base id 0x200
  > instance ipv4: Ipv4 base id 0x300
  > topology Stack {
  >   instance net
  >   instance eth
  >   instance ipv4
  >   connections W {
  >     eth.net -> net.write
  >     ipv4.eth -> eth.write
  >   }
  > }
  > EOF
  $ ofpp to-ml annot_topo.fpp
  [@@@ocamlformat "disable"]
  (* Generated by ofpp to-ml from topology Stack *)
  
  module Eth = Eth.Make(Net)
  module Ipv4 = Ipv4.Make(Eth)
  
  let w = lazy (
    let open Lwt.Syntax in
    let* net = Net.write () in
    let* eth = Eth.write net in
    Ipv4.cidr eth)



Bound leaf instance (@ ocaml.module)
  $ ofpp to-ml data/bound-leaf.fpp
  [@@@ocamlformat "disable"]
  (* Generated by ofpp to-ml from topology T *)
  
  module Kv = Embedded_data
  module Srv = Srv.Make(Kv)
  
  let w = lazy (
    let open Lwt.Syntax in
    let* kv = Kv.get () in
    Srv.connect kv)









External types in port declarations
  $ cat > ext_types.fpp <<EOF
  > @ ocaml.type Cstruct.t
  > type Buffer
  > type Macaddr
  > port Write(data: Buffer)
  > port GetMac -> Macaddr
  > active component Net {
  >   sync input port write: Write
  >   sync input port mac: GetMac
  > }
  > active component Eth {
  >   output port net: Write
  > }
  > instance net: Net base id 0x100
  > instance eth: Eth base id 0x200
  > topology T {
  >   instance net
  >   instance eth
  >   connections C { eth.net -> net.write }
  > }
  > EOF
  $ ofpp to-ml ext_types.fpp
  [@@@ocamlformat "disable"]
  (* Generated by ofpp to-ml from topology T *)
  
  module Eth = Eth.Make(Net)
  
  let c = lazy (
    let open Lwt.Syntax in
    let* net = Net.write ~mac in
    Eth.connect net)



Entry point generation (--topologies generates topology + entry point)
  $ cat > main_topo.fpp <<EOF
  > port P
  > port Dep
  > @ ocaml.module Srv.Make
  > active component Srv { output port kv: Dep }
  > active component Kv { sync input port get: P }
  > instance kv: Kv base id 0x100
  > instance srv: Srv base id 0x200
  > topology T {
  >   @ ocaml.module Embedded_data
  >   instance kv
  >   instance srv
  >   connections W { srv.kv -> kv.get }
  > }
  > EOF
  $ ofpp to-ml --topologies T main_topo.fpp
  [@@@ocamlformat "disable"]
  (* Generated by ofpp to-ml from topology T *)
  
  module Kv = Embedded_data
  module Srv = Srv.Make(Kv)
  
  let w = lazy (
    let open Lwt.Syntax in
    let* kv = Kv.get () in
    Srv.connect kv)
  let mirage_runtime_delay__key = Mirage_runtime.register_arg @@ Mirage_runtime.delay
  let mirage_runtime_logs__key = Mirage_runtime.register_arg @@ Mirage_runtime.logs
  let cmdliner_stdlib__key = Mirage_runtime.register_arg @@
    Cmdliner_stdlib.setup ~backtrace:(Some true) ~randomize_hashtables:(Some true) ()
  
  let () =
    let t =
      let open Lwt.Syntax in
      let* () = Lwt.return (Mirage_runtime.(with_argv (runtime_args ()) "T" (Mirage_bootvar.argv ()))) in
      let _ = cmdliner_stdlib__key () in
      let* () = Mirage_sleep.ns (Duration.of_sec (mirage_runtime_delay__key ())) in
      let reporter = Mirage_logs.create () in
      Mirage_runtime.set_level ~default:(Some Logs.Info) (mirage_runtime_logs__key ());
      Logs.set_reporter reporter;
      let* _ = Mirage_crypto_rng_mirage.initialize (module Mirage_crypto_rng.Fortuna) in
      Mirage_runtime.set_name "T";
      let* _ = Lazy.force w in
      Lwt.return ()
    in
    Unix_os.Main.run t; exit 0










