[@@@ocamlformat "disable"]
(* Generated by ofpp to-ml from topology DirectNetwork. *)

module Net : sig type t end
module Ethernet : sig type t end
module Arp : sig type t end
module Ipv4 : sig type t end
module Ipv6 : sig type t end
module Ip : sig type t end
module Icmp : sig type t end
module Udp : sig type t end
module Tcp : sig type t end
module Stack : sig type t end
module Stack_app : sig end

val connect : Stack.t Lwt.t Lazy.t

val start : unit Lwt.t Lazy.t
