[@@@ocamlformat "disable"]
(* Generated by ofpp to-ml from topology DirectNetwork. *)

module Net : Mirage_net.S
module Ethernet : Ethernet.S
module Arp : Arp.S
module Ipv4 : Tcpip.Ip.S
module Ipv6 : Tcpip.Ip.S
module Ip : Tcpip.Ip.S
module Icmp : Icmpv4.S
module Udp : Tcpip.Udp.S
module Tcp : Tcpip.Tcp.S
module Stack : Tcpip.Stack.V4V6
module Stack_app : sig end

val connect : Stack.t Lwt.t Lazy.t

val start : unit Lwt.t Lazy.t
