[@@@ocamlformat "disable"]

(* Generated by ofpp to-ml from topology DirectNetwork *)

module Net = Vnetif.Make(Backend)
module Ethernet = Ethernet.Make(Net)
module Arp = Arp.Make(Ethernet)
module Ipv4 = Static_ipv4.Make(Ethernet)(Arp)
module Ipv6 = Ipv6.Make(Net)(Ethernet)
module Ip = Tcpip_stack_direct.IPV4V6(Ipv4)(Ipv6)
module Icmp = Icmpv4.Make(Ipv4)
module Udp = Udp.Make(Ip)
module Tcp = Tcp.Flow.Make(Ip)
module Stack = Tcpip_stack_direct.MakeV4V6(Net)(Ethernet)(Arp)(Ip)(Icmp)(Udp)(Tcp)
module Stack_app = Unikernel.Main(Stack)
let ipv6__no_init =
  let doc = Cmdliner.Arg.info ~doc:"no_init" ["ipv6-no-init"] in
  Mirage_runtime.register_arg Cmdliner.Arg.(value & opt bool false doc)

open Lwt.Syntax

let connect = lazy (
  let* backend = Backend.connect () in
  let* net = Net.connect backend in
  let* ethernet = Ethernet.connect net in
  let* arp = Arp.connect ethernet in
  let* ipv4 = Ipv4.connect ~cidr:(Ipaddr.V4.Prefix.of_string_exn "10.0.0.2/24") ethernet arp in
  let* ipv6 = Ipv6.connect ~no_init:(ipv6__no_init ()) net ethernet in
  let* ip = Ip.connect ~ipv4_only:false ~ipv6_only:false ipv4 ipv6 in
  let* icmp = Icmp.connect ipv4 in
  let* udp = Udp.connect ip in
  let* tcp = Tcp.connect ip in
  Stack.connect net ethernet arp ip icmp udp tcp)

let start = lazy (
  let* stack = Lazy.force connect in
  Stack_app.start stack)
let mirage_runtime_delay__key = Mirage_runtime.register_arg @@ Mirage_runtime.delay
let mirage_runtime_logs__key = Mirage_runtime.register_arg @@ Mirage_runtime.logs
let cmdliner_stdlib__key = Mirage_runtime.register_arg @@
  Cmdliner_stdlib.setup ~backtrace:(Some true) ~randomize_hashtables:(Some true) ()

let () =
  let t =
    let open Lwt.Syntax in
    let* () = Lwt.return (Mirage_runtime.(with_argv (runtime_args ()) "DirectNetwork" (Mirage_bootvar.argv ()))) in
    let _ = cmdliner_stdlib__key () in
    let* () = Mirage_sleep.ns (Duration.of_sec (mirage_runtime_delay__key ())) in
    let reporter = Mirage_logs.create () in
    Mirage_runtime.set_level ~default:(Some Logs.Info) (mirage_runtime_logs__key ());
    Logs.set_reporter reporter;
    let* _ = Mirage_crypto_rng_mirage.initialize (module Mirage_crypto_rng.Fortuna) in
    Mirage_runtime.set_name "DirectNetwork";
    let* _ = Lazy.force start in
    Lwt.return ()
  in
  Unix_os.Main.run t; exit 0
