[@@@ocamlformat "disable"]
(* Generated by ofpp to-ml from topology UnixTarKv. *)

module type Ramdisk = Mirage_block.S
module type Tar_kv = Mirage_kv.RO
module Tar_kv : Tar_kv
module Unikernel : sig end

val start : unit Lwt.t Lazy.t
