[@@@ocamlformat "disable"]

module type Udpv4v6_socket = Tcpip.Udp.S
module type Tcpv4v6_socket = Tcpip.Tcp.S
module type Stackv4v6 = Tcpip.Stack.V4V6
(* Generated by ofpp to-ml from topology UnixNetwork *)

module Stackv4v6 = Stackv4v6.Make(Udpv4v6_socket)(Tcpv4v6_socket)
module Unikernel = Unikernel.Main(Stackv4v6)
let unikernel__port =
  let doc = Cmdliner.Arg.info ~doc:"port" ["port"] in
  Mirage_runtime.register_arg Cmdliner.Arg.(value & opt int 8080 doc)

open Lwt.Syntax

let connect = lazy (
  let* udpv4v6_socket = Udpv4v6_socket.connect ~ipv4_only:false ~ipv6_only:false (Ipaddr.V4.Prefix.of_string_exn "0.0.0.0/0") None in
  let* tcpv4v6_socket = Tcpv4v6_socket.connect ~ipv4_only:false ~ipv6_only:false (Ipaddr.V4.Prefix.of_string_exn "0.0.0.0/0") None in
  Stackv4v6.connect udpv4v6_socket tcpv4v6_socket)

let start = lazy (
  let* stackv4v6 = Lazy.force connect in
  Unikernel.start ~port:(unikernel__port ()) stackv4v6)
let mirage_runtime_delay__key = Mirage_runtime.register_arg @@ Mirage_runtime.delay
let mirage_runtime_logs__key = Mirage_runtime.register_arg @@ Mirage_runtime.logs
let cmdliner_stdlib__key = Mirage_runtime.register_arg @@
  Cmdliner_stdlib.setup ~backtrace:(Some true) ~randomize_hashtables:(Some true) ()

let () =
  let t =
    let open Lwt.Syntax in
    let* () = Lwt.return (Mirage_runtime.(with_argv (runtime_args ()) "UnixNetwork" (Mirage_bootvar.argv ()))) in
    let _ = cmdliner_stdlib__key () in
    let* () = Mirage_sleep.ns (Duration.of_sec (mirage_runtime_delay__key ())) in
    let reporter = Mirage_logs.create () in
    Mirage_runtime.set_level ~default:(Some Logs.Info) (mirage_runtime_logs__key ());
    Logs.set_reporter reporter;
    let* _ = Mirage_crypto_rng_mirage.initialize (module Mirage_crypto_rng.Fortuna) in
    Mirage_runtime.set_name "UnixNetwork";
    let* _ = Lazy.force start in
    Lwt.return ()
  in
  Unix_os.Main.run t; exit 0
