[@@@ocamlformat "disable"]
(* Generated by ofpp to-ml from topology UnixNetwork. *)

module Stackv4v6 : Tcpip.Stack.V4V6
module Stack_app : sig end

val connect : Stackv4v6.t Lwt.t Lazy.t

val start : unit Lwt.t Lazy.t
