[@@@ocamlformat "disable"]
(* Generated by ofpp to-ml from topology UnixFatKv. *)

module type Ramdisk = Mirage_block.S
module type Fat_kv = Mirage_kv.RO
module Fat_kv : Fat_kv
module Unikernel : sig end

val start : unit Lwt.t Lazy.t
