[@@@ocamlformat "disable"]
(* Generated by ofpp to-ml from topology UnixLittlefs. *)

module type Block = Mirage_block.S
module type Chamelon = Mirage_kv.RW
module Chamelon : Chamelon
module Unikernel : sig end

val start : unit Lwt.t Lazy.t
