[@@@ocamlformat "disable"]

module type Block = Mirage_block.S
module type Chamelon = Mirage_kv.RW
(* Generated by ofpp to-ml from topology UnixLittlefs *)

module Chamelon = Kv.Make(Block)
module Unikernel = Unikernel.Make(Chamelon)

open Lwt.Syntax

let start = lazy (
  let* block = Block.connect "littlefs" in
  let* chamelon = Chamelon.connect ~program_block_size:16 block in
  Unikernel.start chamelon)
let mirage_runtime_delay__key = Mirage_runtime.register_arg @@ Mirage_runtime.delay
let mirage_runtime_logs__key = Mirage_runtime.register_arg @@ Mirage_runtime.logs
let cmdliner_stdlib__key = Mirage_runtime.register_arg @@
  Cmdliner_stdlib.setup ~backtrace:(Some true) ~randomize_hashtables:(Some true) ()

let () =
  let t =
    let open Lwt.Syntax in
    let* () = Lwt.return (Mirage_runtime.(with_argv (runtime_args ()) "UnixLittlefs" (Mirage_bootvar.argv ()))) in
    let _ = cmdliner_stdlib__key () in
    let* () = Mirage_sleep.ns (Duration.of_sec (mirage_runtime_delay__key ())) in
    let reporter = Mirage_logs.create () in
    Mirage_runtime.set_level ~default:(Some Logs.Info) (mirage_runtime_logs__key ());
    Logs.set_reporter reporter;
    let* _ = Mirage_crypto_rng_mirage.initialize (module Mirage_crypto_rng.Fortuna) in
    Mirage_runtime.set_name "UnixLittlefs";
    let* _ = Lazy.force start in
    Lwt.return ()
  in
  Unix_os.Main.run t; exit 0
