[@@@ocamlformat "disable"]
(* Generated by ofpp to-ml from topology UnixHttpFetch. *)

module type Udpv4v6_socket = Tcpip.Udp.S
module type Tcpv4v6_socket = Tcpip.Tcp.S
module type Stackv4v6 = Tcpip.Stack.V4V6
module type Resolver_unix = Resolver_mirage.S
module type Conduit_tcp = Conduit_mirage.S
module type Cohttp_client = Cohttp_mirage.Client.S
module Stackv4v6 : Stackv4v6
module Conduit_tcp : Conduit_tcp
module Cohttp_client : Cohttp_client
module Unikernel : sig end

val connect : Stackv4v6.t Lwt.t Lazy.t

val start : unit Lwt.t Lazy.t
